// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package assessmentsqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ResourceContextType string

const (
	ResourceContextTypeOrganization ResourceContextType = "organization"
	ResourceContextTypeClass        ResourceContextType = "class"
)

func (e *ResourceContextType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceContextType(s)
	case string:
		*e = ResourceContextType(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceContextType: %T", src)
	}
	return nil
}

type NullResourceContextType struct {
	ResourceContextType ResourceContextType `json:"resource_context_type"`
	Valid               bool                `json:"valid"` // Valid is true if ResourceContextType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceContextType) Scan(value interface{}) error {
	if value == nil {
		ns.ResourceContextType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceContextType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceContextType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceContextType), nil
}

type ResourceFileStatus string

const (
	ResourceFileStatusACTIVE   ResourceFileStatus = "ACTIVE"
	ResourceFileStatusARCHIVED ResourceFileStatus = "ARCHIVED"
)

func (e *ResourceFileStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceFileStatus(s)
	case string:
		*e = ResourceFileStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceFileStatus: %T", src)
	}
	return nil
}

type NullResourceFileStatus struct {
	ResourceFileStatus ResourceFileStatus `json:"resource_file_status"`
	Valid              bool               `json:"valid"` // Valid is true if ResourceFileStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceFileStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ResourceFileStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceFileStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceFileStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceFileStatus), nil
}

type ResourceStatus string

const (
	ResourceStatusDRAFT     ResourceStatus = "DRAFT"
	ResourceStatusPUBLISHED ResourceStatus = "PUBLISHED"
	ResourceStatusARCHIVED  ResourceStatus = "ARCHIVED"
)

func (e *ResourceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceStatus(s)
	case string:
		*e = ResourceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceStatus: %T", src)
	}
	return nil
}

type NullResourceStatus struct {
	ResourceStatus ResourceStatus `json:"resource_status"`
	Valid          bool           `json:"valid"` // Valid is true if ResourceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ResourceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceStatus), nil
}

type AcademicTerm struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Name           string             `json:"name"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Assessment struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	ClassSectionID  pgtype.UUID        `json:"class_section_id"`
	Title           string             `json:"title"`
	DurationMinutes int32              `json:"duration_minutes"`
	MaxAttempts     int32              `json:"max_attempts"`
	SettingsJson    []byte             `json:"settings_json"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Revision        int32              `json:"revision"`
	Instructions    pgtype.Text        `json:"instructions"`
	OpensAt         pgtype.Timestamptz `json:"opens_at"`
	ClosesAt        pgtype.Timestamptz `json:"closes_at"`
}

type AssessmentItem struct {
	ID                  pgtype.UUID        `json:"id"`
	OrganizationID      pgtype.UUID        `json:"organization_id"`
	AssessmentID        pgtype.UUID        `json:"assessment_id"`
	AssessmentSectionID pgtype.UUID        `json:"assessment_section_id"`
	QuestionVersionID   pgtype.UUID        `json:"question_version_id"`
	Position            int32              `json:"position"`
	Points              pgtype.Numeric     `json:"points"`
	SettingsJson        []byte             `json:"settings_json"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type AssessmentPublication struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AssessmentID   pgtype.UUID        `json:"assessment_id"`
	Version        int32              `json:"version"`
	SnapshotJson   []byte             `json:"snapshot_json"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AssessmentSection struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AssessmentID   pgtype.UUID        `json:"assessment_id"`
	Title          string             `json:"title"`
	Position       int32              `json:"position"`
	SettingsJson   []byte             `json:"settings_json"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AssessmentTarget struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AssessmentID   pgtype.UUID        `json:"assessment_id"`
	ClassSectionID pgtype.UUID        `json:"class_section_id"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Attempt struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AssessmentID   pgtype.UUID        `json:"assessment_id"`
	StudentUserID  pgtype.UUID        `json:"student_user_id"`
	PublicationID  pgtype.UUID        `json:"publication_id"`
	Status         string             `json:"status"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Score          pgtype.Numeric     `json:"score"`
	MaxScore       pgtype.Numeric     `json:"max_score"`
	GradingStatus  pgtype.Text        `json:"grading_status"`
}

type AttemptAnswer struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AttemptID      pgtype.UUID        `json:"attempt_id"`
	AttemptItemID  pgtype.UUID        `json:"attempt_item_id"`
	AnswerPayload  []byte             `json:"answer_payload"`
	Revision       int64              `json:"revision"`
	AnsweredAt     pgtype.Timestamptz `json:"answered_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AttemptItem struct {
	ID                pgtype.UUID        `json:"id"`
	OrganizationID    pgtype.UUID        `json:"organization_id"`
	AttemptID         pgtype.UUID        `json:"attempt_id"`
	QuestionVersionID pgtype.UUID        `json:"question_version_id"`
	Position          int32              `json:"position"`
	Points            pgtype.Numeric     `json:"points"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	AnswerKeyJson     []byte             `json:"answer_key_json"`
	PromptJson        []byte             `json:"prompt_json"`
	ChoicesJson       []byte             `json:"choices_json"`
	QuestionType      string             `json:"question_type"`
}

type AuditLog struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	ActorUserID    pgtype.UUID        `json:"actor_user_id"`
	ActorType      pgtype.Text        `json:"actor_type"`
	Action         string             `json:"action"`
	ResourceType   pgtype.Text        `json:"resource_type"`
	ResourceID     pgtype.UUID        `json:"resource_id"`
	RequestID      pgtype.Text        `json:"request_id"`
	IpPrefixOrHash pgtype.Text        `json:"ip_prefix_or_hash"`
	UserAgentHash  pgtype.Text        `json:"user_agent_hash"`
	BeforeJson     []byte             `json:"before_json"`
	AfterJson      []byte             `json:"after_json"`
	MetadataJson   []byte             `json:"metadata_json"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ClassSection struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	CourseID       pgtype.UUID        `json:"course_id"`
	Name           string             `json:"name"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ClassTeacher struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	ClassSectionID pgtype.UUID        `json:"class_section_id"`
	MembershipID   pgtype.UUID        `json:"membership_id"`
	Role           string             `json:"role"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Course struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	SubjectID      pgtype.UUID        `json:"subject_id"`
	AcademicTermID pgtype.UUID        `json:"academic_term_id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Enrollment struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	ClassSectionID pgtype.UUID        `json:"class_section_id"`
	MembershipID   pgtype.UUID        `json:"membership_id"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type IdempotencyKey struct {
	ID               pgtype.UUID        `json:"id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	ActorUserID      pgtype.UUID        `json:"actor_user_id"`
	Scope            string             `json:"scope"`
	KeyHash          string             `json:"key_hash"`
	RequestHash      pgtype.Text        `json:"request_hash"`
	ResponseStatus   pgtype.Int4        `json:"response_status"`
	ResponseBodyJson []byte             `json:"response_body_json"`
	ResourceID       pgtype.UUID        `json:"resource_id"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ItemGrade struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AttemptID      pgtype.UUID        `json:"attempt_id"`
	AttemptItemID  pgtype.UUID        `json:"attempt_item_id"`
	GraderUserID   pgtype.UUID        `json:"grader_user_id"`
	AwardedScore   pgtype.Numeric     `json:"awarded_score"`
	Feedback       pgtype.Text        `json:"feedback"`
	GradedAt       pgtype.Timestamptz `json:"graded_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type LoginAttempt struct {
	ID                 pgtype.UUID        `json:"id"`
	OrganizationID     pgtype.UUID        `json:"organization_id"`
	UsernameNormalized string             `json:"username_normalized"`
	AttemptedAt        pgtype.Timestamptz `json:"attempted_at"`
}

type MembershipLoginName struct {
	ID                 pgtype.UUID        `json:"id"`
	OrganizationID     pgtype.UUID        `json:"organization_id"`
	UsernameNormalized string             `json:"username_normalized"`
	UserID             pgtype.UUID        `json:"user_id"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	PasswordHash       pgtype.Text        `json:"password_hash"`
}

type MembershipRole struct {
	MembershipID pgtype.UUID        `json:"membership_id"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationMembership struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PasswordHistory struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Question struct {
	ID             pgtype.UUID        `json:"id"`
	QuestionBankID pgtype.UUID        `json:"question_bank_id"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type QuestionBank struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type QuestionVersion struct {
	ID            pgtype.UUID        `json:"id"`
	QuestionID    pgtype.UUID        `json:"question_id"`
	Version       int32              `json:"version"`
	PromptJson    []byte             `json:"prompt_json"`
	ChoicesJson   []byte             `json:"choices_json"`
	AnswerKeyJson []byte             `json:"answer_key_json"`
	MaxScore      pgtype.Numeric     `json:"max_score"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	QuestionType  string             `json:"question_type"`
}

type RefreshSession struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	MembershipID        pgtype.UUID        `json:"membership_id"`
	OrganizationID      pgtype.UUID        `json:"organization_id"`
	TokenHash           string             `json:"token_hash"`
	FamilyID            pgtype.UUID        `json:"family_id"`
	AuthVersion         int64              `json:"auth_version"`
	DeviceMetadataJson  []byte             `json:"device_metadata_json"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ReplacedByTokenHash pgtype.Text        `json:"replaced_by_token_hash"`
}

type Resource struct {
	ID             pgtype.UUID         `json:"id"`
	OrganizationID pgtype.UUID         `json:"organization_id"`
	Title          string              `json:"title"`
	Description    pgtype.Text         `json:"description"`
	ContextType    ResourceContextType `json:"context_type"`
	ContextID      pgtype.UUID         `json:"context_id"`
	Status         ResourceStatus      `json:"status"`
	CreatedBy      pgtype.UUID         `json:"created_by"`
	CreatedAt      pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz  `json:"updated_at"`
	PublishedAt    pgtype.Timestamptz  `json:"published_at"`
}

type ResourceFile struct {
	ID             pgtype.UUID        `json:"id"`
	ResourceID     pgtype.UUID        `json:"resource_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	OriginalName   string             `json:"original_name"`
	StorageKey     string             `json:"storage_key"`
	ContentType    string             `json:"content_type"`
	SizeBytes      int64              `json:"size_bytes"`
	Status         ResourceFileStatus `json:"status"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Subject struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                 pgtype.UUID        `json:"id"`
	EmailNormalized    pgtype.Text        `json:"email_normalized"`
	Status             string             `json:"status"`
	AuthVersion        int64              `json:"auth_version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	MustChangePassword bool               `json:"must_change_password"`
	Email              pgtype.Text        `json:"email"`
	DisplayName        pgtype.Text        `json:"display_name"`
}
