// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package assessmentsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveAssessmentItem = `-- name: ArchiveAssessmentItem :execrows
UPDATE assessment_items
SET status = 'ARCHIVED',
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND status = 'ACTIVE'
`

type ArchiveAssessmentItemParams struct {
	ItemID         pgtype.UUID `json:"item_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ArchiveAssessmentItem(ctx context.Context, arg ArchiveAssessmentItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveAssessmentItem, arg.ItemID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const archiveAssessmentSection = `-- name: ArchiveAssessmentSection :execrows
UPDATE assessment_sections
SET status = 'ARCHIVED',
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND status = 'ACTIVE'
`

type ArchiveAssessmentSectionParams struct {
	SectionID      pgtype.UUID `json:"section_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ArchiveAssessmentSection(ctx context.Context, arg ArchiveAssessmentSectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveAssessmentSection, arg.SectionID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const archiveAssessmentTarget = `-- name: ArchiveAssessmentTarget :execrows
UPDATE assessment_targets
SET status = 'ARCHIVED',
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND status = 'ACTIVE'
`

type ArchiveAssessmentTargetParams struct {
	TargetID       pgtype.UUID `json:"target_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ArchiveAssessmentTarget(ctx context.Context, arg ArchiveAssessmentTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveAssessmentTarget, arg.TargetID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAssessmentItems = `-- name: CountAssessmentItems :one
SELECT COUNT(*)
FROM assessment_items
WHERE organization_id = $1
  AND assessment_id = $2
  AND status = 'ACTIVE'
`

type CountAssessmentItemsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
}

func (q *Queries) CountAssessmentItems(ctx context.Context, arg CountAssessmentItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssessmentItems, arg.OrganizationID, arg.AssessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAssessmentSections = `-- name: CountAssessmentSections :one
SELECT COUNT(*)
FROM assessment_sections
WHERE organization_id = $1
  AND assessment_id = $2
  AND status = 'ACTIVE'
`

type CountAssessmentSectionsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
}

func (q *Queries) CountAssessmentSections(ctx context.Context, arg CountAssessmentSectionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssessmentSections, arg.OrganizationID, arg.AssessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAssessmentTargets = `-- name: CountAssessmentTargets :one
SELECT COUNT(*)
FROM assessment_targets
WHERE organization_id = $1
  AND assessment_id = $2
  AND status = 'ACTIVE'
`

type CountAssessmentTargetsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
}

func (q *Queries) CountAssessmentTargets(ctx context.Context, arg CountAssessmentTargetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssessmentTargets, arg.OrganizationID, arg.AssessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedByOrganization = `-- name: CountPublishedByOrganization :one
SELECT COUNT(*)
FROM assessments
WHERE organization_id = $1
  AND status IN ('OPEN', 'PUBLISHED')
  AND ($2::text = '' OR title ILIKE '%' || $2 || '%')
`

type CountPublishedByOrganizationParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	SearchQuery    string      `json:"search_query"`
}

func (q *Queries) CountPublishedByOrganization(ctx context.Context, arg CountPublishedByOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedByOrganization, arg.OrganizationID, arg.SearchQuery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuestions = `-- name: CountQuestions :one
SELECT COUNT(*)
FROM questions q
JOIN question_banks qb ON qb.id = q.question_bank_id
LEFT JOIN LATERAL (
    SELECT id, status, prompt_json
    FROM question_versions
    WHERE question_id = q.id
      AND status = 'PUBLISHED'
    ORDER BY version DESC, created_at DESC
    LIMIT 1
) qv ON true
WHERE qb.organization_id = $1
  AND q.status = 'ACTIVE'
  AND ($2::text = '' OR q.question_bank_id::text = $2::text)
  AND ($3::text = '' OR qv.prompt_json ->> 'text' ILIKE '%' || $3 || '%')
`

type CountQuestionsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	BankID         string      `json:"bank_id"`
	SearchQuery    string      `json:"search_query"`
}

func (q *Queries) CountQuestions(ctx context.Context, arg CountQuestionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countQuestions, arg.OrganizationID, arg.BankID, arg.SearchQuery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssessment = `-- name: CreateAssessment :one

INSERT INTO assessments (organization_id, class_section_id, title, duration_minutes, max_attempts, status)
VALUES ($1, $2, $3, $4, $5, 'DRAFT')
RETURNING id, organization_id, class_section_id, title, duration_minutes, max_attempts, settings_json, status, revision, instructions, opens_at, closes_at, created_at, updated_at
`

type CreateAssessmentParams struct {
	OrganizationID  pgtype.UUID `json:"organization_id"`
	ClassSectionID  pgtype.UUID `json:"class_section_id"`
	Title           string      `json:"title"`
	DurationMinutes int32       `json:"duration_minutes"`
	MaxAttempts     int32       `json:"max_attempts"`
}

type CreateAssessmentRow struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	ClassSectionID  pgtype.UUID        `json:"class_section_id"`
	Title           string             `json:"title"`
	DurationMinutes int32              `json:"duration_minutes"`
	MaxAttempts     int32              `json:"max_attempts"`
	SettingsJson    []byte             `json:"settings_json"`
	Status          string             `json:"status"`
	Revision        int32              `json:"revision"`
	Instructions    pgtype.Text        `json:"instructions"`
	OpensAt         pgtype.Timestamptz `json:"opens_at"`
	ClosesAt        pgtype.Timestamptz `json:"closes_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// Assessment builder queries
func (q *Queries) CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (CreateAssessmentRow, error) {
	row := q.db.QueryRow(ctx, createAssessment,
		arg.OrganizationID,
		arg.ClassSectionID,
		arg.Title,
		arg.DurationMinutes,
		arg.MaxAttempts,
	)
	var i CreateAssessmentRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ClassSectionID,
		&i.Title,
		&i.DurationMinutes,
		&i.MaxAttempts,
		&i.SettingsJson,
		&i.Status,
		&i.Revision,
		&i.Instructions,
		&i.OpensAt,
		&i.ClosesAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAssessmentItem = `-- name: CreateAssessmentItem :one
INSERT INTO assessment_items (organization_id, assessment_id, assessment_section_id, question_version_id, position, points)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, assessment_section_id, question_version_id, position, points, status
`

type CreateAssessmentItemParams struct {
	OrganizationID      pgtype.UUID    `json:"organization_id"`
	AssessmentID        pgtype.UUID    `json:"assessment_id"`
	AssessmentSectionID pgtype.UUID    `json:"assessment_section_id"`
	QuestionVersionID   pgtype.UUID    `json:"question_version_id"`
	Position            int32          `json:"position"`
	Points              pgtype.Numeric `json:"points"`
}

type CreateAssessmentItemRow struct {
	ID                  pgtype.UUID    `json:"id"`
	AssessmentSectionID pgtype.UUID    `json:"assessment_section_id"`
	QuestionVersionID   pgtype.UUID    `json:"question_version_id"`
	Position            int32          `json:"position"`
	Points              pgtype.Numeric `json:"points"`
	Status              string         `json:"status"`
}

func (q *Queries) CreateAssessmentItem(ctx context.Context, arg CreateAssessmentItemParams) (CreateAssessmentItemRow, error) {
	row := q.db.QueryRow(ctx, createAssessmentItem,
		arg.OrganizationID,
		arg.AssessmentID,
		arg.AssessmentSectionID,
		arg.QuestionVersionID,
		arg.Position,
		arg.Points,
	)
	var i CreateAssessmentItemRow
	err := row.Scan(
		&i.ID,
		&i.AssessmentSectionID,
		&i.QuestionVersionID,
		&i.Position,
		&i.Points,
		&i.Status,
	)
	return i, err
}

const createAssessmentSection = `-- name: CreateAssessmentSection :one
INSERT INTO assessment_sections (organization_id, assessment_id, title, position)
VALUES ($1, $2, $3, $4)
RETURNING id, assessment_id, title, position, settings_json, status
`

type CreateAssessmentSectionParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
	Title          string      `json:"title"`
	Position       int32       `json:"position"`
}

type CreateAssessmentSectionRow struct {
	ID           pgtype.UUID `json:"id"`
	AssessmentID pgtype.UUID `json:"assessment_id"`
	Title        string      `json:"title"`
	Position     int32       `json:"position"`
	SettingsJson []byte      `json:"settings_json"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateAssessmentSection(ctx context.Context, arg CreateAssessmentSectionParams) (CreateAssessmentSectionRow, error) {
	row := q.db.QueryRow(ctx, createAssessmentSection,
		arg.OrganizationID,
		arg.AssessmentID,
		arg.Title,
		arg.Position,
	)
	var i CreateAssessmentSectionRow
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.Title,
		&i.Position,
		&i.SettingsJson,
		&i.Status,
	)
	return i, err
}

const createAssessmentTarget = `-- name: CreateAssessmentTarget :one
INSERT INTO assessment_targets (organization_id, assessment_id, class_section_id)
VALUES ($1, $2, $3)
RETURNING id, assessment_id, class_section_id, status
`

type CreateAssessmentTargetParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
	ClassSectionID pgtype.UUID `json:"class_section_id"`
}

type CreateAssessmentTargetRow struct {
	ID             pgtype.UUID `json:"id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
	ClassSectionID pgtype.UUID `json:"class_section_id"`
	Status         string      `json:"status"`
}

func (q *Queries) CreateAssessmentTarget(ctx context.Context, arg CreateAssessmentTargetParams) (CreateAssessmentTargetRow, error) {
	row := q.db.QueryRow(ctx, createAssessmentTarget, arg.OrganizationID, arg.AssessmentID, arg.ClassSectionID)
	var i CreateAssessmentTargetRow
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.ClassSectionID,
		&i.Status,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (question_bank_id)
VALUES ($1)
RETURNING id, question_bank_id, status, created_at, updated_at
`

func (q *Queries) CreateQuestion(ctx context.Context, questionBankID pgtype.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion, questionBankID)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuestionBankID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuestionBank = `-- name: CreateQuestionBank :one

INSERT INTO question_banks (organization_id, title)
VALUES ($1, $2)
RETURNING id, organization_id, title, status, created_at, updated_at
`

type CreateQuestionBankParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Title          string      `json:"title"`
}

// Question bank editor queries
func (q *Queries) CreateQuestionBank(ctx context.Context, arg CreateQuestionBankParams) (QuestionBank, error) {
	row := q.db.QueryRow(ctx, createQuestionBank, arg.OrganizationID, arg.Title)
	var i QuestionBank
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuestionVersion = `-- name: CreateQuestionVersion :one
INSERT INTO question_versions (
    question_id, version, prompt_json, choices_json, answer_key_json, max_score, status, question_type
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, question_id, version, prompt_json, choices_json, answer_key_json, max_score, status, question_type, created_at
`

type CreateQuestionVersionParams struct {
	QuestionID    pgtype.UUID    `json:"question_id"`
	Version       int32          `json:"version"`
	PromptJson    []byte         `json:"prompt_json"`
	ChoicesJson   []byte         `json:"choices_json"`
	AnswerKeyJson []byte         `json:"answer_key_json"`
	MaxScore      pgtype.Numeric `json:"max_score"`
	Status        string         `json:"status"`
	QuestionType  string         `json:"question_type"`
}

type CreateQuestionVersionRow struct {
	ID            pgtype.UUID        `json:"id"`
	QuestionID    pgtype.UUID        `json:"question_id"`
	Version       int32              `json:"version"`
	PromptJson    []byte             `json:"prompt_json"`
	ChoicesJson   []byte             `json:"choices_json"`
	AnswerKeyJson []byte             `json:"answer_key_json"`
	MaxScore      pgtype.Numeric     `json:"max_score"`
	Status        string             `json:"status"`
	QuestionType  string             `json:"question_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateQuestionVersion(ctx context.Context, arg CreateQuestionVersionParams) (CreateQuestionVersionRow, error) {
	row := q.db.QueryRow(ctx, createQuestionVersion,
		arg.QuestionID,
		arg.Version,
		arg.PromptJson,
		arg.ChoicesJson,
		arg.AnswerKeyJson,
		arg.MaxScore,
		arg.Status,
		arg.QuestionType,
	)
	var i CreateQuestionVersionRow
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Version,
		&i.PromptJson,
		&i.ChoicesJson,
		&i.AnswerKeyJson,
		&i.MaxScore,
		&i.Status,
		&i.QuestionType,
		&i.CreatedAt,
	)
	return i, err
}

const getAssessment = `-- name: GetAssessment :one
SELECT id, organization_id, class_section_id, title, duration_minutes, max_attempts, settings_json, status, revision, instructions, opens_at, closes_at, created_at, updated_at
FROM assessments
WHERE id = $1
  AND organization_id = $2
`

type GetAssessmentParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetAssessmentRow struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	ClassSectionID  pgtype.UUID        `json:"class_section_id"`
	Title           string             `json:"title"`
	DurationMinutes int32              `json:"duration_minutes"`
	MaxAttempts     int32              `json:"max_attempts"`
	SettingsJson    []byte             `json:"settings_json"`
	Status          string             `json:"status"`
	Revision        int32              `json:"revision"`
	Instructions    pgtype.Text        `json:"instructions"`
	OpensAt         pgtype.Timestamptz `json:"opens_at"`
	ClosesAt        pgtype.Timestamptz `json:"closes_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAssessment(ctx context.Context, arg GetAssessmentParams) (GetAssessmentRow, error) {
	row := q.db.QueryRow(ctx, getAssessment, arg.ID, arg.OrganizationID)
	var i GetAssessmentRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ClassSectionID,
		&i.Title,
		&i.DurationMinutes,
		&i.MaxAttempts,
		&i.SettingsJson,
		&i.Status,
		&i.Revision,
		&i.Instructions,
		&i.OpensAt,
		&i.ClosesAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssessmentItem = `-- name: GetAssessmentItem :one
SELECT id, assessment_section_id, question_version_id, position, points, status
FROM assessment_items
WHERE id = $1
  AND organization_id = $2
`

type GetAssessmentItemParams struct {
	ItemID         pgtype.UUID `json:"item_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetAssessmentItemRow struct {
	ID                  pgtype.UUID    `json:"id"`
	AssessmentSectionID pgtype.UUID    `json:"assessment_section_id"`
	QuestionVersionID   pgtype.UUID    `json:"question_version_id"`
	Position            int32          `json:"position"`
	Points              pgtype.Numeric `json:"points"`
	Status              string         `json:"status"`
}

func (q *Queries) GetAssessmentItem(ctx context.Context, arg GetAssessmentItemParams) (GetAssessmentItemRow, error) {
	row := q.db.QueryRow(ctx, getAssessmentItem, arg.ItemID, arg.OrganizationID)
	var i GetAssessmentItemRow
	err := row.Scan(
		&i.ID,
		&i.AssessmentSectionID,
		&i.QuestionVersionID,
		&i.Position,
		&i.Points,
		&i.Status,
	)
	return i, err
}

const getAssessmentItems = `-- name: GetAssessmentItems :many
SELECT id, assessment_section_id, question_version_id, position, points, status
FROM assessment_items
WHERE organization_id = $1
  AND assessment_id = $2
  AND status = 'ACTIVE'
ORDER BY assessment_section_id, position
`

type GetAssessmentItemsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
}

type GetAssessmentItemsRow struct {
	ID                  pgtype.UUID    `json:"id"`
	AssessmentSectionID pgtype.UUID    `json:"assessment_section_id"`
	QuestionVersionID   pgtype.UUID    `json:"question_version_id"`
	Position            int32          `json:"position"`
	Points              pgtype.Numeric `json:"points"`
	Status              string         `json:"status"`
}

func (q *Queries) GetAssessmentItems(ctx context.Context, arg GetAssessmentItemsParams) ([]GetAssessmentItemsRow, error) {
	rows, err := q.db.Query(ctx, getAssessmentItems, arg.OrganizationID, arg.AssessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssessmentItemsRow
	for rows.Next() {
		var i GetAssessmentItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentSectionID,
			&i.QuestionVersionID,
			&i.Position,
			&i.Points,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssessmentItemsBySection = `-- name: GetAssessmentItemsBySection :many
SELECT id, assessment_section_id, question_version_id, position, points, status
FROM assessment_items
WHERE organization_id = $1
  AND assessment_section_id = $2
  AND status = 'ACTIVE'
ORDER BY position
`

type GetAssessmentItemsBySectionParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	SectionID      pgtype.UUID `json:"section_id"`
}

type GetAssessmentItemsBySectionRow struct {
	ID                  pgtype.UUID    `json:"id"`
	AssessmentSectionID pgtype.UUID    `json:"assessment_section_id"`
	QuestionVersionID   pgtype.UUID    `json:"question_version_id"`
	Position            int32          `json:"position"`
	Points              pgtype.Numeric `json:"points"`
	Status              string         `json:"status"`
}

func (q *Queries) GetAssessmentItemsBySection(ctx context.Context, arg GetAssessmentItemsBySectionParams) ([]GetAssessmentItemsBySectionRow, error) {
	rows, err := q.db.Query(ctx, getAssessmentItemsBySection, arg.OrganizationID, arg.SectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssessmentItemsBySectionRow
	for rows.Next() {
		var i GetAssessmentItemsBySectionRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentSectionID,
			&i.QuestionVersionID,
			&i.Position,
			&i.Points,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssessmentItemsWithContent = `-- name: GetAssessmentItemsWithContent :many
SELECT ai.id, ai.assessment_section_id, ai.question_version_id, ai.position, ai.points,
       qv.prompt_json, qv.choices_json, qv.answer_key_json, qv.max_score, qv.question_type
FROM assessment_items ai
JOIN question_versions qv ON qv.id = ai.question_version_id
WHERE ai.organization_id = $1
  AND ai.assessment_id = $2
  AND ai.status = 'ACTIVE'
ORDER BY ai.assessment_section_id, ai.position
`

type GetAssessmentItemsWithContentParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
}

type GetAssessmentItemsWithContentRow struct {
	ID                  pgtype.UUID    `json:"id"`
	AssessmentSectionID pgtype.UUID    `json:"assessment_section_id"`
	QuestionVersionID   pgtype.UUID    `json:"question_version_id"`
	Position            int32          `json:"position"`
	Points              pgtype.Numeric `json:"points"`
	PromptJson          []byte         `json:"prompt_json"`
	ChoicesJson         []byte         `json:"choices_json"`
	AnswerKeyJson       []byte         `json:"answer_key_json"`
	MaxScore            pgtype.Numeric `json:"max_score"`
	QuestionType        string         `json:"question_type"`
}

func (q *Queries) GetAssessmentItemsWithContent(ctx context.Context, arg GetAssessmentItemsWithContentParams) ([]GetAssessmentItemsWithContentRow, error) {
	rows, err := q.db.Query(ctx, getAssessmentItemsWithContent, arg.OrganizationID, arg.AssessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssessmentItemsWithContentRow
	for rows.Next() {
		var i GetAssessmentItemsWithContentRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentSectionID,
			&i.QuestionVersionID,
			&i.Position,
			&i.Points,
			&i.PromptJson,
			&i.ChoicesJson,
			&i.AnswerKeyJson,
			&i.MaxScore,
			&i.QuestionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssessmentRevision = `-- name: GetAssessmentRevision :one
SELECT revision
FROM assessments
WHERE id = $1
  AND organization_id = $2
`

type GetAssessmentRevisionParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetAssessmentRevision(ctx context.Context, arg GetAssessmentRevisionParams) (int32, error) {
	row := q.db.QueryRow(ctx, getAssessmentRevision, arg.ID, arg.OrganizationID)
	var revision int32
	err := row.Scan(&revision)
	return revision, err
}

const getAssessmentSection = `-- name: GetAssessmentSection :one
SELECT id, assessment_id, title, position, settings_json, status
FROM assessment_sections
WHERE id = $1
  AND organization_id = $2
`

type GetAssessmentSectionParams struct {
	SectionID      pgtype.UUID `json:"section_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetAssessmentSectionRow struct {
	ID           pgtype.UUID `json:"id"`
	AssessmentID pgtype.UUID `json:"assessment_id"`
	Title        string      `json:"title"`
	Position     int32       `json:"position"`
	SettingsJson []byte      `json:"settings_json"`
	Status       string      `json:"status"`
}

func (q *Queries) GetAssessmentSection(ctx context.Context, arg GetAssessmentSectionParams) (GetAssessmentSectionRow, error) {
	row := q.db.QueryRow(ctx, getAssessmentSection, arg.SectionID, arg.OrganizationID)
	var i GetAssessmentSectionRow
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.Title,
		&i.Position,
		&i.SettingsJson,
		&i.Status,
	)
	return i, err
}

const getAssessmentSections = `-- name: GetAssessmentSections :many
SELECT id, assessment_id, title, position, settings_json, status
FROM assessment_sections
WHERE organization_id = $1
  AND assessment_id = $2
  AND status = 'ACTIVE'
ORDER BY position
`

type GetAssessmentSectionsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
}

type GetAssessmentSectionsRow struct {
	ID           pgtype.UUID `json:"id"`
	AssessmentID pgtype.UUID `json:"assessment_id"`
	Title        string      `json:"title"`
	Position     int32       `json:"position"`
	SettingsJson []byte      `json:"settings_json"`
	Status       string      `json:"status"`
}

func (q *Queries) GetAssessmentSections(ctx context.Context, arg GetAssessmentSectionsParams) ([]GetAssessmentSectionsRow, error) {
	rows, err := q.db.Query(ctx, getAssessmentSections, arg.OrganizationID, arg.AssessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssessmentSectionsRow
	for rows.Next() {
		var i GetAssessmentSectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.Title,
			&i.Position,
			&i.SettingsJson,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssessmentTarget = `-- name: GetAssessmentTarget :one
SELECT id, assessment_id, class_section_id, status
FROM assessment_targets
WHERE id = $1
  AND organization_id = $2
`

type GetAssessmentTargetParams struct {
	TargetID       pgtype.UUID `json:"target_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetAssessmentTargetRow struct {
	ID             pgtype.UUID `json:"id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
	ClassSectionID pgtype.UUID `json:"class_section_id"`
	Status         string      `json:"status"`
}

func (q *Queries) GetAssessmentTarget(ctx context.Context, arg GetAssessmentTargetParams) (GetAssessmentTargetRow, error) {
	row := q.db.QueryRow(ctx, getAssessmentTarget, arg.TargetID, arg.OrganizationID)
	var i GetAssessmentTargetRow
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.ClassSectionID,
		&i.Status,
	)
	return i, err
}

const getAssessmentTargets = `-- name: GetAssessmentTargets :many
SELECT id, assessment_id, class_section_id, status
FROM assessment_targets
WHERE organization_id = $1
  AND assessment_id = $2
  AND status = 'ACTIVE'
`

type GetAssessmentTargetsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
}

type GetAssessmentTargetsRow struct {
	ID             pgtype.UUID `json:"id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
	ClassSectionID pgtype.UUID `json:"class_section_id"`
	Status         string      `json:"status"`
}

func (q *Queries) GetAssessmentTargets(ctx context.Context, arg GetAssessmentTargetsParams) ([]GetAssessmentTargetsRow, error) {
	rows, err := q.db.Query(ctx, getAssessmentTargets, arg.OrganizationID, arg.AssessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssessmentTargetsRow
	for rows.Next() {
		var i GetAssessmentTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.ClassSectionID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemAssessmentID = `-- name: GetItemAssessmentID :one
SELECT assessment_id
FROM assessment_items
WHERE id = $1
  AND organization_id = $2
`

type GetItemAssessmentIDParams struct {
	ItemID         pgtype.UUID `json:"item_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetItemAssessmentID(ctx context.Context, arg GetItemAssessmentIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getItemAssessmentID, arg.ItemID, arg.OrganizationID)
	var assessment_id pgtype.UUID
	err := row.Scan(&assessment_id)
	return assessment_id, err
}

const getLatestVersionNumber = `-- name: GetLatestVersionNumber :one
SELECT COALESCE(MAX(version), 0)::int AS version
FROM question_versions
WHERE question_id = $1
`

func (q *Queries) GetLatestVersionNumber(ctx context.Context, questionID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getLatestVersionNumber, questionID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, question_bank_id, status, created_at, updated_at
FROM questions
WHERE id = $1
  AND question_bank_id = $2
`

type GetQuestionParams struct {
	ID     pgtype.UUID `json:"id"`
	BankID pgtype.UUID `json:"bank_id"`
}

func (q *Queries) GetQuestion(ctx context.Context, arg GetQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestion, arg.ID, arg.BankID)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuestionBankID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuestionBank = `-- name: GetQuestionBank :one
SELECT id, organization_id, title, status, created_at, updated_at
FROM question_banks
WHERE id = $1
  AND organization_id = $2
`

type GetQuestionBankParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetQuestionBank(ctx context.Context, arg GetQuestionBankParams) (QuestionBank, error) {
	row := q.db.QueryRow(ctx, getQuestionBank, arg.ID, arg.OrganizationID)
	var i QuestionBank
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuestionVersion = `-- name: GetQuestionVersion :one
SELECT qv.id, qv.question_id, qv.version, qv.prompt_json, qv.choices_json, qv.answer_key_json, qv.max_score, qv.status, qv.question_type, qv.created_at
FROM question_versions qv
JOIN questions q ON q.id = qv.question_id
JOIN question_banks qb ON qb.id = q.question_bank_id
WHERE qv.id = $1
  AND qb.organization_id = $2
`

type GetQuestionVersionParams struct {
	VersionID      pgtype.UUID `json:"version_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetQuestionVersionRow struct {
	ID            pgtype.UUID        `json:"id"`
	QuestionID    pgtype.UUID        `json:"question_id"`
	Version       int32              `json:"version"`
	PromptJson    []byte             `json:"prompt_json"`
	ChoicesJson   []byte             `json:"choices_json"`
	AnswerKeyJson []byte             `json:"answer_key_json"`
	MaxScore      pgtype.Numeric     `json:"max_score"`
	Status        string             `json:"status"`
	QuestionType  string             `json:"question_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetQuestionVersion(ctx context.Context, arg GetQuestionVersionParams) (GetQuestionVersionRow, error) {
	row := q.db.QueryRow(ctx, getQuestionVersion, arg.VersionID, arg.OrganizationID)
	var i GetQuestionVersionRow
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Version,
		&i.PromptJson,
		&i.ChoicesJson,
		&i.AnswerKeyJson,
		&i.MaxScore,
		&i.Status,
		&i.QuestionType,
		&i.CreatedAt,
	)
	return i, err
}

const getQuestionWithBank = `-- name: GetQuestionWithBank :one
SELECT q.id, q.question_bank_id, qb.organization_id, q.status, q.created_at, q.updated_at
FROM questions q
JOIN question_banks qb ON qb.id = q.question_bank_id
WHERE q.id = $1
`

type GetQuestionWithBankRow struct {
	ID             pgtype.UUID        `json:"id"`
	QuestionBankID pgtype.UUID        `json:"question_bank_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetQuestionWithBank(ctx context.Context, id pgtype.UUID) (GetQuestionWithBankRow, error) {
	row := q.db.QueryRow(ctx, getQuestionWithBank, id)
	var i GetQuestionWithBankRow
	err := row.Scan(
		&i.ID,
		&i.QuestionBankID,
		&i.OrganizationID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSectionAssessmentID = `-- name: GetSectionAssessmentID :one
SELECT assessment_id
FROM assessment_sections
WHERE id = $1
  AND organization_id = $2
`

type GetSectionAssessmentIDParams struct {
	SectionID      pgtype.UUID `json:"section_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetSectionAssessmentID(ctx context.Context, arg GetSectionAssessmentIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSectionAssessmentID, arg.SectionID, arg.OrganizationID)
	var assessment_id pgtype.UUID
	err := row.Scan(&assessment_id)
	return assessment_id, err
}

const getTargetAssessmentID = `-- name: GetTargetAssessmentID :one
SELECT assessment_id
FROM assessment_targets
WHERE id = $1
  AND organization_id = $2
`

type GetTargetAssessmentIDParams struct {
	TargetID       pgtype.UUID `json:"target_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetTargetAssessmentID(ctx context.Context, arg GetTargetAssessmentIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getTargetAssessmentID, arg.TargetID, arg.OrganizationID)
	var assessment_id pgtype.UUID
	err := row.Scan(&assessment_id)
	return assessment_id, err
}

const insertAssessmentPublication = `-- name: InsertAssessmentPublication :one
INSERT INTO assessment_publications (organization_id, assessment_id, version, snapshot_json, published_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, version, snapshot_json, published_at
`

type InsertAssessmentPublicationParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
	Version        int32       `json:"version"`
	SnapshotJson   []byte      `json:"snapshot_json"`
}

type InsertAssessmentPublicationRow struct {
	ID           pgtype.UUID        `json:"id"`
	Version      int32              `json:"version"`
	SnapshotJson []byte             `json:"snapshot_json"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) InsertAssessmentPublication(ctx context.Context, arg InsertAssessmentPublicationParams) (InsertAssessmentPublicationRow, error) {
	row := q.db.QueryRow(ctx, insertAssessmentPublication,
		arg.OrganizationID,
		arg.AssessmentID,
		arg.Version,
		arg.SnapshotJson,
	)
	var i InsertAssessmentPublicationRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.SnapshotJson,
		&i.PublishedAt,
	)
	return i, err
}

const isAssessmentManager = `-- name: IsAssessmentManager :one
SELECT EXISTS (
    SELECT 1
    FROM organization_memberships m
    JOIN membership_roles mr ON mr.membership_id = m.id
    WHERE m.organization_id = $1
      AND m.user_id = $2
      AND m.status = 'ACTIVE'
      AND mr.role = 'admin'
) OR EXISTS (
    SELECT 1
    FROM organization_memberships m
    JOIN class_teachers ct ON ct.membership_id = m.id AND ct.status = 'ACTIVE'
    WHERE m.organization_id = $1
      AND m.user_id = $2
      AND m.status = 'ACTIVE'
      AND (
          ct.class_section_id = (SELECT a.class_section_id FROM assessments a WHERE a.id = $3 AND a.organization_id = $1)
          OR ct.class_section_id IN (
              SELECT class_section_id FROM assessment_targets
              WHERE assessment_id = $3 AND organization_id = $1 AND status = 'ACTIVE'
          )
      )
)
`

type IsAssessmentManagerParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
}

func (q *Queries) IsAssessmentManager(ctx context.Context, arg IsAssessmentManagerParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isAssessmentManager, arg.OrganizationID, arg.UserID, arg.AssessmentID)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const isClassManager = `-- name: IsClassManager :one
SELECT EXISTS (
    SELECT 1
    FROM organization_memberships m
    JOIN membership_roles mr ON mr.membership_id = m.id
    WHERE m.organization_id = $1
      AND m.user_id = $2
      AND m.status = 'ACTIVE'
      AND mr.role = 'admin'
) OR EXISTS (
    SELECT 1
    FROM organization_memberships m
    JOIN class_teachers ct ON ct.membership_id = m.id AND ct.status = 'ACTIVE'
    WHERE m.organization_id = $1
      AND m.user_id = $2
      AND m.status = 'ACTIVE'
      AND ct.class_section_id = $3
)
`

type IsClassManagerParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	ClassSectionID pgtype.UUID `json:"class_section_id"`
}

func (q *Queries) IsClassManager(ctx context.Context, arg IsClassManagerParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isClassManager, arg.OrganizationID, arg.UserID, arg.ClassSectionID)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const isClassSectionActive = `-- name: IsClassSectionActive :one
SELECT EXISTS (
    SELECT 1
    FROM class_sections
    WHERE id = $1
      AND organization_id = $2
      AND status = 'ACTIVE'
)
`

type IsClassSectionActiveParams struct {
	ClassSectionID pgtype.UUID `json:"class_section_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) IsClassSectionActive(ctx context.Context, arg IsClassSectionActiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, isClassSectionActive, arg.ClassSectionID, arg.OrganizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isQuestionVersionPublished = `-- name: IsQuestionVersionPublished :one
SELECT EXISTS (
    SELECT 1
    FROM question_versions qv
    JOIN questions q ON q.id = qv.question_id
    JOIN question_banks qb ON qb.id = q.question_bank_id
    WHERE qv.id = $1
      AND qb.organization_id = $2
      AND qv.status = 'PUBLISHED'
)
`

type IsQuestionVersionPublishedParams struct {
	QuestionVersionID pgtype.UUID `json:"question_version_id"`
	OrganizationID    pgtype.UUID `json:"organization_id"`
}

func (q *Queries) IsQuestionVersionPublished(ctx context.Context, arg IsQuestionVersionPublishedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isQuestionVersionPublished, arg.QuestionVersionID, arg.OrganizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAssessmentPublications = `-- name: ListAssessmentPublications :many
SELECT ap.id, ap.version, a.status, ap.published_at
FROM assessment_publications ap
JOIN assessments a ON a.id = ap.assessment_id AND a.organization_id = ap.organization_id
WHERE ap.organization_id = $1
  AND ap.assessment_id = $2
ORDER BY ap.version DESC
`

type ListAssessmentPublicationsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
}

type ListAssessmentPublicationsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Version     int32              `json:"version"`
	Status      string             `json:"status"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ListAssessmentPublications(ctx context.Context, arg ListAssessmentPublicationsParams) ([]ListAssessmentPublicationsRow, error) {
	rows, err := q.db.Query(ctx, listAssessmentPublications, arg.OrganizationID, arg.AssessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssessmentPublicationsRow
	for rows.Next() {
		var i ListAssessmentPublicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Status,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssessmentsByClass = `-- name: ListAssessmentsByClass :many
SELECT a.id, a.title, a.status, a.duration_minutes, a.revision, a.opens_at, a.closes_at, a.created_at
FROM assessments a
JOIN assessment_targets t ON t.assessment_id = a.id AND t.status = 'ACTIVE'
WHERE a.organization_id = $1
  AND t.class_section_id = $2
  AND a.status != 'ARCHIVED'
ORDER BY a.created_at DESC
`

type ListAssessmentsByClassParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ClassSectionID pgtype.UUID `json:"class_section_id"`
}

type ListAssessmentsByClassRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	Status          string             `json:"status"`
	DurationMinutes int32              `json:"duration_minutes"`
	Revision        int32              `json:"revision"`
	OpensAt         pgtype.Timestamptz `json:"opens_at"`
	ClosesAt        pgtype.Timestamptz `json:"closes_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAssessmentsByClass(ctx context.Context, arg ListAssessmentsByClassParams) ([]ListAssessmentsByClassRow, error) {
	rows, err := q.db.Query(ctx, listAssessmentsByClass, arg.OrganizationID, arg.ClassSectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssessmentsByClassRow
	for rows.Next() {
		var i ListAssessmentsByClassRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.DurationMinutes,
			&i.Revision,
			&i.OpensAt,
			&i.ClosesAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedByOrganization = `-- name: ListPublishedByOrganization :many
SELECT id, title, status, duration_minutes, created_at
FROM assessments
WHERE organization_id = $1
  AND status IN ('OPEN', 'PUBLISHED')
  AND ($2::text = '' OR title ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR created_at < $3::timestamptz OR (created_at = $3::timestamptz AND id::text < $4))
ORDER BY created_at DESC, id DESC
LIMIT NULLIF($6::int, 0) OFFSET $5::int
`

type ListPublishedByOrganizationParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	SearchQuery    string      `json:"search_query"`
	CursorKey      string      `json:"cursor_key"`
	CursorID       pgtype.UUID `json:"cursor_id"`
	PageOffset     int32       `json:"page_offset"`
	PageLimit      int32       `json:"page_limit"`
}

type ListPublishedByOrganizationRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	Status          string             `json:"status"`
	DurationMinutes int32              `json:"duration_minutes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPublishedByOrganization(ctx context.Context, arg ListPublishedByOrganizationParams) ([]ListPublishedByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listPublishedByOrganization,
		arg.OrganizationID,
		arg.SearchQuery,
		arg.CursorKey,
		arg.CursorID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedByOrganizationRow
	for rows.Next() {
		var i ListPublishedByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.DurationMinutes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionBanksByOrganization = `-- name: ListQuestionBanksByOrganization :many
SELECT id, organization_id, title, status, created_at, updated_at
FROM question_banks
WHERE organization_id = $1
  AND ($2::bool OR status = 'ACTIVE')
ORDER BY created_at DESC
LIMIT NULLIF($4::int, 0) OFFSET $3::int
`

type ListQuestionBanksByOrganizationParams struct {
	OrganizationID  pgtype.UUID `json:"organization_id"`
	IncludeArchived bool        `json:"include_archived"`
	PageOffset      int32       `json:"page_offset"`
	PageLimit       int32       `json:"page_limit"`
}

func (q *Queries) ListQuestionBanksByOrganization(ctx context.Context, arg ListQuestionBanksByOrganizationParams) ([]QuestionBank, error) {
	rows, err := q.db.Query(ctx, listQuestionBanksByOrganization,
		arg.OrganizationID,
		arg.IncludeArchived,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionBank
	for rows.Next() {
		var i QuestionBank
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestions = `-- name: ListQuestions :many
SELECT q.id, q.question_bank_id, COALESCE(qv.id, '00000000-0000-0000-0000-000000000000'::uuid) AS question_version_id, COALESCE(qv.status, '') AS question_version_status, COALESCE(qv.question_type, '') AS question_type, qv.prompt_json ->> 'text' AS prompt_text
FROM questions q
JOIN question_banks qb ON qb.id = q.question_bank_id
LEFT JOIN LATERAL (
    SELECT id, status, prompt_json, question_type
    FROM question_versions
    WHERE question_id = q.id
      AND status = 'PUBLISHED'
    ORDER BY version DESC, created_at DESC
    LIMIT 1
) qv ON true
WHERE qb.organization_id = $1
  AND q.status = 'ACTIVE'
  AND ($2::text = '' OR q.question_bank_id::text = $2::text)
  AND ($3::text = '' OR qv.prompt_json ->> 'text' ILIKE '%' || $3 || '%')
ORDER BY q.created_at DESC
LIMIT NULLIF($5::int, 0) OFFSET $4::int
`

type ListQuestionsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	BankID         string      `json:"bank_id"`
	SearchQuery    string      `json:"search_query"`
	PageOffset     int32       `json:"page_offset"`
	PageLimit      int32       `json:"page_limit"`
}

type ListQuestionsRow struct {
	ID                    pgtype.UUID `json:"id"`
	QuestionBankID        pgtype.UUID `json:"question_bank_id"`
	QuestionVersionID     pgtype.UUID `json:"question_version_id"`
	QuestionVersionStatus string      `json:"question_version_status"`
	QuestionType          string      `json:"question_type"`
	PromptText            interface{} `json:"prompt_text"`
}

func (q *Queries) ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]ListQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listQuestions,
		arg.OrganizationID,
		arg.BankID,
		arg.SearchQuery,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestionsRow
	for rows.Next() {
		var i ListQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionBankID,
			&i.QuestionVersionID,
			&i.QuestionVersionStatus,
			&i.QuestionType,
			&i.PromptText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsInBank = `-- name: ListQuestionsInBank :many
SELECT q.id, q.question_bank_id, q.status, q.created_at, q.updated_at,
       qv.id AS latest_version_id, qv.status AS latest_version_status,
       qv.question_type, qv.version AS latest_version
FROM questions q
LEFT JOIN LATERAL (
    SELECT id, status, question_type, version
    FROM question_versions
    WHERE question_id = q.id
    ORDER BY version DESC, created_at DESC
    LIMIT 1
) qv ON true
WHERE q.question_bank_id = $1
  AND ($2::bool OR q.status = 'ACTIVE')
ORDER BY q.created_at DESC
LIMIT NULLIF($4::int, 0) OFFSET $3::int
`

type ListQuestionsInBankParams struct {
	BankID          pgtype.UUID `json:"bank_id"`
	IncludeArchived bool        `json:"include_archived"`
	PageOffset      int32       `json:"page_offset"`
	PageLimit       int32       `json:"page_limit"`
}

type ListQuestionsInBankRow struct {
	ID                  pgtype.UUID        `json:"id"`
	QuestionBankID      pgtype.UUID        `json:"question_bank_id"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	LatestVersionID     pgtype.UUID        `json:"latest_version_id"`
	LatestVersionStatus string             `json:"latest_version_status"`
	QuestionType        string             `json:"question_type"`
	LatestVersion       int32              `json:"latest_version"`
}

func (q *Queries) ListQuestionsInBank(ctx context.Context, arg ListQuestionsInBankParams) ([]ListQuestionsInBankRow, error) {
	rows, err := q.db.Query(ctx, listQuestionsInBank,
		arg.BankID,
		arg.IncludeArchived,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestionsInBankRow
	for rows.Next() {
		var i ListQuestionsInBankRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionBankID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LatestVersionID,
			&i.LatestVersionStatus,
			&i.QuestionType,
			&i.LatestVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishAssessment = `-- name: PublishAssessment :execrows
UPDATE assessments
SET status = $1,
    revision = revision + 1,
    updated_at = now()
WHERE id = $2
  AND organization_id = $3
  AND status = 'DRAFT'
`

type PublishAssessmentParams struct {
	NewStatus      string      `json:"new_status"`
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) PublishAssessment(ctx context.Context, arg PublishAssessmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, publishAssessment, arg.NewStatus, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const publishQuestionVersion = `-- name: PublishQuestionVersion :one
UPDATE question_versions
SET status = 'PUBLISHED',
    created_at = created_at
WHERE id = $1
  AND status = 'DRAFT'
RETURNING id, question_id, version, prompt_json, choices_json, answer_key_json, max_score, status, question_type, created_at
`

type PublishQuestionVersionRow struct {
	ID            pgtype.UUID        `json:"id"`
	QuestionID    pgtype.UUID        `json:"question_id"`
	Version       int32              `json:"version"`
	PromptJson    []byte             `json:"prompt_json"`
	ChoicesJson   []byte             `json:"choices_json"`
	AnswerKeyJson []byte             `json:"answer_key_json"`
	MaxScore      pgtype.Numeric     `json:"max_score"`
	Status        string             `json:"status"`
	QuestionType  string             `json:"question_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) PublishQuestionVersion(ctx context.Context, versionID pgtype.UUID) (PublishQuestionVersionRow, error) {
	row := q.db.QueryRow(ctx, publishQuestionVersion, versionID)
	var i PublishQuestionVersionRow
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Version,
		&i.PromptJson,
		&i.ChoicesJson,
		&i.AnswerKeyJson,
		&i.MaxScore,
		&i.Status,
		&i.QuestionType,
		&i.CreatedAt,
	)
	return i, err
}

const questionVersionExists = `-- name: QuestionVersionExists :one
SELECT EXISTS (
    SELECT 1
    FROM question_versions qv
    JOIN questions q ON q.id = qv.question_id
    JOIN question_banks qb ON qb.id = q.question_bank_id
    WHERE qv.id = $1
      AND qb.organization_id = $2
      AND qv.status = 'PUBLISHED'
)
`

type QuestionVersionExistsParams struct {
	QuestionVersionID pgtype.UUID `json:"question_version_id"`
	OrganizationID    pgtype.UUID `json:"organization_id"`
}

func (q *Queries) QuestionVersionExists(ctx context.Context, arg QuestionVersionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, questionVersionExists, arg.QuestionVersionID, arg.OrganizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const transitionAssessmentsToClosed = `-- name: TransitionAssessmentsToClosed :execrows
UPDATE assessments
SET status = 'CLOSED',
    updated_at = now()
WHERE status = 'OPEN'
  AND closes_at IS NOT NULL
  AND closes_at <= now()
`

// Scheduler: transition open assessments to closed when closes_at passes.
func (q *Queries) TransitionAssessmentsToClosed(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, transitionAssessmentsToClosed)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transitionAssessmentsToOpen = `-- name: TransitionAssessmentsToOpen :execrows
UPDATE assessments
SET status = 'OPEN',
    updated_at = now()
WHERE status IN ('SCHEDULED', 'PUBLISHED')
  AND opens_at IS NOT NULL
  AND opens_at <= now()
`

// Scheduler: transition published/scheduled assessments to open when opens_at passes.
func (q *Queries) TransitionAssessmentsToOpen(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, transitionAssessmentsToOpen)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAssessmentItem = `-- name: UpdateAssessmentItem :one
UPDATE assessment_items
SET question_version_id = COALESCE(NULLIF($1::uuid, '00000000-0000-0000-0000-000000000000'::uuid), question_version_id),
    points = COALESCE(NULLIF($2::numeric, '0'::numeric), points),
    position = $3,
    updated_at = now()
WHERE id = $4
  AND organization_id = $5
  AND status = 'ACTIVE'
RETURNING id, assessment_section_id, question_version_id, position, points, status
`

type UpdateAssessmentItemParams struct {
	QuestionVersionID pgtype.UUID    `json:"question_version_id"`
	Points            pgtype.Numeric `json:"points"`
	Position          int32          `json:"position"`
	ItemID            pgtype.UUID    `json:"item_id"`
	OrganizationID    pgtype.UUID    `json:"organization_id"`
}

type UpdateAssessmentItemRow struct {
	ID                  pgtype.UUID    `json:"id"`
	AssessmentSectionID pgtype.UUID    `json:"assessment_section_id"`
	QuestionVersionID   pgtype.UUID    `json:"question_version_id"`
	Position            int32          `json:"position"`
	Points              pgtype.Numeric `json:"points"`
	Status              string         `json:"status"`
}

func (q *Queries) UpdateAssessmentItem(ctx context.Context, arg UpdateAssessmentItemParams) (UpdateAssessmentItemRow, error) {
	row := q.db.QueryRow(ctx, updateAssessmentItem,
		arg.QuestionVersionID,
		arg.Points,
		arg.Position,
		arg.ItemID,
		arg.OrganizationID,
	)
	var i UpdateAssessmentItemRow
	err := row.Scan(
		&i.ID,
		&i.AssessmentSectionID,
		&i.QuestionVersionID,
		&i.Position,
		&i.Points,
		&i.Status,
	)
	return i, err
}

const updateAssessmentItemPosition = `-- name: UpdateAssessmentItemPosition :execrows
UPDATE assessment_items
SET position = $1,
    updated_at = now()
WHERE id = $2
  AND organization_id = $3
  AND status = 'ACTIVE'
`

type UpdateAssessmentItemPositionParams struct {
	Position       int32       `json:"position"`
	ItemID         pgtype.UUID `json:"item_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) UpdateAssessmentItemPosition(ctx context.Context, arg UpdateAssessmentItemPositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAssessmentItemPosition, arg.Position, arg.ItemID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAssessmentSection = `-- name: UpdateAssessmentSection :one
UPDATE assessment_sections
SET title = COALESCE(NULLIF($1::text, ''), title),
    position = $2,
    updated_at = now()
WHERE id = $3
  AND organization_id = $4
  AND status = 'ACTIVE'
RETURNING id, assessment_id, title, position, settings_json, status
`

type UpdateAssessmentSectionParams struct {
	Title          string      `json:"title"`
	Position       int32       `json:"position"`
	SectionID      pgtype.UUID `json:"section_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type UpdateAssessmentSectionRow struct {
	ID           pgtype.UUID `json:"id"`
	AssessmentID pgtype.UUID `json:"assessment_id"`
	Title        string      `json:"title"`
	Position     int32       `json:"position"`
	SettingsJson []byte      `json:"settings_json"`
	Status       string      `json:"status"`
}

func (q *Queries) UpdateAssessmentSection(ctx context.Context, arg UpdateAssessmentSectionParams) (UpdateAssessmentSectionRow, error) {
	row := q.db.QueryRow(ctx, updateAssessmentSection,
		arg.Title,
		arg.Position,
		arg.SectionID,
		arg.OrganizationID,
	)
	var i UpdateAssessmentSectionRow
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.Title,
		&i.Position,
		&i.SettingsJson,
		&i.Status,
	)
	return i, err
}

const updateAssessmentSectionPosition = `-- name: UpdateAssessmentSectionPosition :execrows
UPDATE assessment_sections
SET position = $1,
    updated_at = now()
WHERE id = $2
  AND organization_id = $3
  AND status = 'ACTIVE'
`

type UpdateAssessmentSectionPositionParams struct {
	Position       int32       `json:"position"`
	SectionID      pgtype.UUID `json:"section_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) UpdateAssessmentSectionPosition(ctx context.Context, arg UpdateAssessmentSectionPositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAssessmentSectionPosition, arg.Position, arg.SectionID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAssessmentSettings = `-- name: UpdateAssessmentSettings :execrows
UPDATE assessments
SET title = $1,
    duration_minutes = $2,
    max_attempts = $3,
    instructions = $4,
    opens_at = $5,
    closes_at = $6,
    settings_json = $7,
    updated_at = now()
WHERE id = $8
  AND organization_id = $9
  AND status = 'DRAFT'
`

type UpdateAssessmentSettingsParams struct {
	Title           string             `json:"title"`
	DurationMinutes int32              `json:"duration_minutes"`
	MaxAttempts     int32              `json:"max_attempts"`
	Instructions    pgtype.Text        `json:"instructions"`
	OpensAt         pgtype.Timestamptz `json:"opens_at"`
	ClosesAt        pgtype.Timestamptz `json:"closes_at"`
	SettingsJson    []byte             `json:"settings_json"`
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
}

func (q *Queries) UpdateAssessmentSettings(ctx context.Context, arg UpdateAssessmentSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAssessmentSettings,
		arg.Title,
		arg.DurationMinutes,
		arg.MaxAttempts,
		arg.Instructions,
		arg.OpensAt,
		arg.ClosesAt,
		arg.SettingsJson,
		arg.ID,
		arg.OrganizationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
