// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package assessmentsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPublishedByOrganization = `-- name: ListPublishedByOrganization :many
SELECT id, title, status, duration_minutes
FROM assessments
WHERE organization_id = $1
  AND status IN ('OPEN', 'PUBLISHED')
  AND ($2::text = '' OR title ILIKE '%' || $2 || '%')
ORDER BY created_at DESC
LIMIT NULLIF($3::int, 0) OFFSET $4::int
`

type ListPublishedByOrganizationParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Column2        string      `json:"column_2"`
	Column3        int32       `json:"column_3"`
	Column4        int32       `json:"column_4"`
}

type ListPublishedByOrganizationRow struct {
	ID              pgtype.UUID `json:"id"`
	Title           string      `json:"title"`
	Status          string      `json:"status"`
	DurationMinutes int32       `json:"duration_minutes"`
}

func (q *Queries) ListPublishedByOrganization(ctx context.Context, arg ListPublishedByOrganizationParams) ([]ListPublishedByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listPublishedByOrganization,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedByOrganizationRow
	for rows.Next() {
		var i ListPublishedByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.DurationMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
