// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package gradingsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAttemptForGrading = `-- name: GetAttemptForGrading :one
SELECT
    a.id,
    a.organization_id,
    a.assessment_id,
    a.student_user_id,
    a.publication_id,
    a.status,
    a.started_at,
    a.expires_at,
    a.submitted_at,
    a.score,
    a.max_score,
    a.grading_status
FROM attempts a
WHERE a.id = $1
  AND a.organization_id = $2
LIMIT 1
`

type GetAttemptForGradingParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetAttemptForGradingRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AssessmentID   pgtype.UUID        `json:"assessment_id"`
	StudentUserID  pgtype.UUID        `json:"student_user_id"`
	PublicationID  pgtype.UUID        `json:"publication_id"`
	Status         string             `json:"status"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	Score          pgtype.Numeric     `json:"score"`
	MaxScore       pgtype.Numeric     `json:"max_score"`
	GradingStatus  pgtype.Text        `json:"grading_status"`
}

// Org-scoped attempt (no student_user_id filter) for teacher/admin review.
func (q *Queries) GetAttemptForGrading(ctx context.Context, arg GetAttemptForGradingParams) (GetAttemptForGradingRow, error) {
	row := q.db.QueryRow(ctx, getAttemptForGrading, arg.ID, arg.OrganizationID)
	var i GetAttemptForGradingRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AssessmentID,
		&i.StudentUserID,
		&i.PublicationID,
		&i.Status,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.Score,
		&i.MaxScore,
		&i.GradingStatus,
	)
	return i, err
}

const getAttemptItemForGrading = `-- name: GetAttemptItemForGrading :one
SELECT
    ai.id,
    ai.organization_id,
    ai.attempt_id,
    ai.question_version_id,
    ai.position,
    ai.points::text AS points,
    ai.question_type,
    aa.answer_payload
FROM attempt_items ai
LEFT JOIN attempt_answers aa
    ON aa.attempt_item_id = ai.id
    AND aa.organization_id = ai.organization_id
    AND aa.attempt_id = ai.attempt_id
WHERE ai.id = $1
  AND ai.organization_id = $2
LIMIT 1
`

type GetAttemptItemForGradingParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetAttemptItemForGradingRow struct {
	ID                pgtype.UUID `json:"id"`
	OrganizationID    pgtype.UUID `json:"organization_id"`
	AttemptID         pgtype.UUID `json:"attempt_id"`
	QuestionVersionID pgtype.UUID `json:"question_version_id"`
	Position          int32       `json:"position"`
	Points            string      `json:"points"`
	QuestionType      string      `json:"question_type"`
	AnswerPayload     []byte      `json:"answer_payload"`
}

func (q *Queries) GetAttemptItemForGrading(ctx context.Context, arg GetAttemptItemForGradingParams) (GetAttemptItemForGradingRow, error) {
	row := q.db.QueryRow(ctx, getAttemptItemForGrading, arg.ID, arg.OrganizationID)
	var i GetAttemptItemForGradingRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AttemptID,
		&i.QuestionVersionID,
		&i.Position,
		&i.Points,
		&i.QuestionType,
		&i.AnswerPayload,
	)
	return i, err
}

const getAttemptItemsForGrading = `-- name: GetAttemptItemsForGrading :many
SELECT
    ai.id,
    ai.organization_id,
    ai.attempt_id,
    ai.question_version_id,
    ai.position,
    ai.points::text AS points,
    ai.prompt_json,
    ai.choices_json,
    ai.answer_key_json,
    ai.question_type,
    aa.answer_payload,
    aa.revision,
    aa.answered_at,
    ig.id AS item_grade_id,
    COALESCE(ig.awarded_score, '0')::text AS awarded_score,
    COALESCE(ig.feedback, '') AS feedback,
    ig.grader_user_id,
    ig.graded_at
FROM attempt_items ai
LEFT JOIN attempt_answers aa
    ON aa.attempt_item_id = ai.id
    AND aa.organization_id = ai.organization_id
    AND aa.attempt_id = ai.attempt_id
LEFT JOIN item_grades ig
    ON ig.attempt_item_id = ai.id
    AND ig.organization_id = ai.organization_id
WHERE ai.attempt_id = $1
  AND ai.organization_id = $2
ORDER BY ai.position
`

type GetAttemptItemsForGradingParams struct {
	AttemptID      pgtype.UUID `json:"attempt_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetAttemptItemsForGradingRow struct {
	ID                pgtype.UUID        `json:"id"`
	OrganizationID    pgtype.UUID        `json:"organization_id"`
	AttemptID         pgtype.UUID        `json:"attempt_id"`
	QuestionVersionID pgtype.UUID        `json:"question_version_id"`
	Position          int32              `json:"position"`
	Points            string             `json:"points"`
	PromptJson        []byte             `json:"prompt_json"`
	ChoicesJson       []byte             `json:"choices_json"`
	AnswerKeyJson     []byte             `json:"answer_key_json"`
	QuestionType      string             `json:"question_type"`
	AnswerPayload     []byte             `json:"answer_payload"`
	Revision          pgtype.Int8        `json:"revision"`
	AnsweredAt        pgtype.Timestamptz `json:"answered_at"`
	ItemGradeID       pgtype.UUID        `json:"item_grade_id"`
	AwardedScore      string             `json:"awarded_score"`
	Feedback          string             `json:"feedback"`
	GraderUserID      pgtype.UUID        `json:"grader_user_id"`
	GradedAt          pgtype.Timestamptz `json:"graded_at"`
}

// Items in an attempt joined with any current manual grade.
func (q *Queries) GetAttemptItemsForGrading(ctx context.Context, arg GetAttemptItemsForGradingParams) ([]GetAttemptItemsForGradingRow, error) {
	rows, err := q.db.Query(ctx, getAttemptItemsForGrading, arg.AttemptID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttemptItemsForGradingRow
	for rows.Next() {
		var i GetAttemptItemsForGradingRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.AttemptID,
			&i.QuestionVersionID,
			&i.Position,
			&i.Points,
			&i.PromptJson,
			&i.ChoicesJson,
			&i.AnswerKeyJson,
			&i.QuestionType,
			&i.AnswerPayload,
			&i.Revision,
			&i.AnsweredAt,
			&i.ItemGradeID,
			&i.AwardedScore,
			&i.Feedback,
			&i.GraderUserID,
			&i.GradedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemGrade = `-- name: GetItemGrade :one
SELECT
    id, organization_id, attempt_id, attempt_item_id, grader_user_id,
    awarded_score::text AS awarded_score, COALESCE(feedback, '') AS feedback, graded_at, created_at, updated_at
FROM item_grades
WHERE organization_id = $1
  AND attempt_item_id = $2
LIMIT 1
`

type GetItemGradeParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AttemptItemID  pgtype.UUID `json:"attempt_item_id"`
}

type GetItemGradeRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AttemptID      pgtype.UUID        `json:"attempt_id"`
	AttemptItemID  pgtype.UUID        `json:"attempt_item_id"`
	GraderUserID   pgtype.UUID        `json:"grader_user_id"`
	AwardedScore   string             `json:"awarded_score"`
	Feedback       string             `json:"feedback"`
	GradedAt       pgtype.Timestamptz `json:"graded_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetItemGrade(ctx context.Context, arg GetItemGradeParams) (GetItemGradeRow, error) {
	row := q.db.QueryRow(ctx, getItemGrade, arg.OrganizationID, arg.AttemptItemID)
	var i GetItemGradeRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AttemptID,
		&i.AttemptItemID,
		&i.GraderUserID,
		&i.AwardedScore,
		&i.Feedback,
		&i.GradedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemGradeByID = `-- name: GetItemGradeByID :one
SELECT
    id, organization_id, attempt_id, attempt_item_id, grader_user_id,
    awarded_score::text AS awarded_score, COALESCE(feedback, '') AS feedback, graded_at, created_at, updated_at
FROM item_grades
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetItemGradeByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetItemGradeByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AttemptID      pgtype.UUID        `json:"attempt_id"`
	AttemptItemID  pgtype.UUID        `json:"attempt_item_id"`
	GraderUserID   pgtype.UUID        `json:"grader_user_id"`
	AwardedScore   string             `json:"awarded_score"`
	Feedback       string             `json:"feedback"`
	GradedAt       pgtype.Timestamptz `json:"graded_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetItemGradeByID(ctx context.Context, arg GetItemGradeByIDParams) (GetItemGradeByIDRow, error) {
	row := q.db.QueryRow(ctx, getItemGradeByID, arg.ID, arg.OrganizationID)
	var i GetItemGradeByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AttemptID,
		&i.AttemptItemID,
		&i.GraderUserID,
		&i.AwardedScore,
		&i.Feedback,
		&i.GradedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReviewQueue = `-- name: ListReviewQueue :many
SELECT
    a.id AS attempt_id,
    a.organization_id,
    a.assessment_id,
    a.student_user_id,
    u.display_name AS student_name,
    a.status,
    a.started_at,
    a.submitted_at,
    a.expires_at,
    a.max_score,
    COALESCE(pending.pending_items, 0)::int AS pending_items,
    COALESCE(pending.total_non_mcq, 0)::int AS total_non_mcq
FROM attempts a
JOIN users u ON u.id = a.student_user_id
JOIN LATERAL (
    SELECT
        COUNT(*) FILTER (
            WHERE ai.question_type IN ('essay', 'short_answer') AND ig.id IS NULL
        ) AS pending_items,
        COUNT(*) FILTER (
            WHERE ai.question_type IN ('essay', 'short_answer')
        ) AS total_non_mcq
    FROM attempt_items ai
    LEFT JOIN item_grades ig
        ON ig.attempt_item_id = ai.id
        AND ig.organization_id = ai.organization_id
    WHERE ai.attempt_id = a.id
      AND ai.organization_id = a.organization_id
) pending ON true
WHERE a.organization_id = $1
  AND a.assessment_id = $2
  AND a.status IN ('SUBMITTED', 'EXPIRED')
  AND a.grading_status = 'PENDING_REVIEW'
ORDER BY a.submitted_at ASC NULLS LAST, a.started_at ASC
`

type ListReviewQueueParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
}

type ListReviewQueueRow struct {
	AttemptID      pgtype.UUID        `json:"attempt_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AssessmentID   pgtype.UUID        `json:"assessment_id"`
	StudentUserID  pgtype.UUID        `json:"student_user_id"`
	StudentName    pgtype.Text        `json:"student_name"`
	Status         string             `json:"status"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	MaxScore       pgtype.Numeric     `json:"max_score"`
	PendingItems   int32              `json:"pending_items"`
	TotalNonMcq    int32              `json:"total_non_mcq"`
}

// Pending-review attempts + the count of ungraded non-MCQ items for each.
func (q *Queries) ListReviewQueue(ctx context.Context, arg ListReviewQueueParams) ([]ListReviewQueueRow, error) {
	rows, err := q.db.Query(ctx, listReviewQueue, arg.OrganizationID, arg.AssessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewQueueRow
	for rows.Next() {
		var i ListReviewQueueRow
		if err := rows.Scan(
			&i.AttemptID,
			&i.OrganizationID,
			&i.AssessmentID,
			&i.StudentUserID,
			&i.StudentName,
			&i.Status,
			&i.StartedAt,
			&i.SubmittedAt,
			&i.ExpiresAt,
			&i.MaxScore,
			&i.PendingItems,
			&i.TotalNonMcq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeAttemptScore = `-- name: RecomputeAttemptScore :one
WITH per_item AS (
    SELECT
        ai.id,
        ai.question_type,
        ai.points::numeric AS points,
        ig.id AS grade_id
    FROM attempt_items ai
    LEFT JOIN item_grades ig
        ON ig.attempt_item_id = ai.id
        AND ig.organization_id = ai.organization_id
    WHERE ai.attempt_id = $1
      AND ai.organization_id = $2
),
auto_grade AS (
    -- MCQ auto-grade on submit is preserved; we don't recompute MCQ correctness
    -- here. If a manual item_grade exists for an MCQ we trust the awarded_score.
    SELECT
        COALESCE(SUM(COALESCE(ig.awarded_score, 0)), 0)::numeric AS score,
        COALESCE(SUM(pi.points), 0)::numeric AS max_score,
        BOOL_OR(
            pi.question_type IN ('essay', 'short_answer') AND pi.grade_id IS NULL
        ) AS has_pending
    FROM per_item pi
    LEFT JOIN item_grades ig
        ON ig.attempt_item_id = pi.id
        AND ig.organization_id = $2
)
UPDATE attempts
SET score = ag.score,
    max_score = ag.max_score,
    grading_status = CASE WHEN ag.has_pending THEN 'PENDING_REVIEW' ELSE 'GRADED' END,
    updated_at = now()
FROM auto_grade ag
WHERE attempts.id = $1
  AND attempts.organization_id = $2
RETURNING attempts.id, attempts.score::text AS score, attempts.max_score::text AS max_score, attempts.grading_status
`

type RecomputeAttemptScoreParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type RecomputeAttemptScoreRow struct {
	ID            pgtype.UUID `json:"id"`
	Score         string      `json:"score"`
	MaxScore      string      `json:"max_score"`
	GradingStatus pgtype.Text `json:"grading_status"`
}

// Recompute the attempt's score from the sum of item-level grades and
// promote the attempt to GRADED only when every non-MCQ item has a grade.
func (q *Queries) RecomputeAttemptScore(ctx context.Context, arg RecomputeAttemptScoreParams) (RecomputeAttemptScoreRow, error) {
	row := q.db.QueryRow(ctx, recomputeAttemptScore, arg.ID, arg.OrganizationID)
	var i RecomputeAttemptScoreRow
	err := row.Scan(
		&i.ID,
		&i.Score,
		&i.MaxScore,
		&i.GradingStatus,
	)
	return i, err
}

const upsertItemGrade = `-- name: UpsertItemGrade :one
INSERT INTO item_grades (
    organization_id,
    attempt_id,
    attempt_item_id,
    grader_user_id,
    awarded_score,
    feedback,
    graded_at,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, now(), now(), now())
ON CONFLICT (organization_id, attempt_item_id) DO UPDATE SET
    grader_user_id = EXCLUDED.grader_user_id,
    awarded_score = EXCLUDED.awarded_score,
    feedback = EXCLUDED.feedback,
    graded_at = now(),
    updated_at = now()
RETURNING id, organization_id, attempt_id, attempt_item_id, grader_user_id, awarded_score::text AS awarded_score, feedback, graded_at, created_at, updated_at
`

type UpsertItemGradeParams struct {
	OrganizationID pgtype.UUID    `json:"organization_id"`
	AttemptID      pgtype.UUID    `json:"attempt_id"`
	AttemptItemID  pgtype.UUID    `json:"attempt_item_id"`
	GraderUserID   pgtype.UUID    `json:"grader_user_id"`
	AwardedScore   pgtype.Numeric `json:"awarded_score"`
	Feedback       pgtype.Text    `json:"feedback"`
}

type UpsertItemGradeRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AttemptID      pgtype.UUID        `json:"attempt_id"`
	AttemptItemID  pgtype.UUID        `json:"attempt_item_id"`
	GraderUserID   pgtype.UUID        `json:"grader_user_id"`
	AwardedScore   string             `json:"awarded_score"`
	Feedback       pgtype.Text        `json:"feedback"`
	GradedAt       pgtype.Timestamptz `json:"graded_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertItemGrade(ctx context.Context, arg UpsertItemGradeParams) (UpsertItemGradeRow, error) {
	row := q.db.QueryRow(ctx, upsertItemGrade,
		arg.OrganizationID,
		arg.AttemptID,
		arg.AttemptItemID,
		arg.GraderUserID,
		arg.AwardedScore,
		arg.Feedback,
	)
	var i UpsertItemGradeRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AttemptID,
		&i.AttemptItemID,
		&i.GraderUserID,
		&i.AwardedScore,
		&i.Feedback,
		&i.GradedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
