// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package adminsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpAuthVersion = `-- name: BumpAuthVersion :exec
UPDATE users
SET auth_version = auth_version + 1
WHERE id = $1
`

func (q *Queries) BumpAuthVersion(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bumpAuthVersion, id)
	return err
}

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*)
FROM audit_logs
WHERE organization_id = $1
  AND ($2::text = '' OR action = $2)
  AND ($3::text = '' OR actor_user_id::text = $3)
  AND ($4::text = '' OR created_at >= $4::timestamptz)
  AND ($5::text = '' OR created_at <= $5::timestamptz)
`

type CountAuditLogsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ActionName     string      `json:"action_name"`
	ActorUserID    string      `json:"actor_user_id"`
	FromTime       string      `json:"from_time"`
	ToTime         string      `json:"to_time"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.OrganizationID,
		arg.ActionName,
		arg.ActorUserID,
		arg.FromTime,
		arg.ToTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)
FROM users u
JOIN organization_memberships m ON m.user_id = u.id
JOIN membership_login_names ln ON ln.user_id = u.id AND ln.organization_id = m.organization_id
WHERE m.organization_id = $1
  AND m.status = 'ACTIVE'
  AND ln.status = 'ACTIVE'
  AND ($2::text = '' OR ln.username_normalized ILIKE '%' || $2 || '%' OR u.display_name ILIKE '%' || $2 || '%' OR u.email ILIKE '%' || $2 || '%')
`

type CountUsersParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	SearchQuery    string      `json:"search_query"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.OrganizationID, arg.SearchQuery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLoginName = `-- name: CreateLoginName :exec
INSERT INTO membership_login_names (organization_id, username_normalized, user_id, password_hash)
VALUES ($1, lower($2), $3, $4)
`

type CreateLoginNameParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Lower          string      `json:"lower"`
	UserID         pgtype.UUID `json:"user_id"`
	PasswordHash   pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateLoginName(ctx context.Context, arg CreateLoginNameParams) error {
	_, err := q.db.Exec(ctx, createLoginName,
		arg.OrganizationID,
		arg.Lower,
		arg.UserID,
		arg.PasswordHash,
	)
	return err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO organization_memberships (organization_id, user_id)
VALUES ($1, $2)
RETURNING id
`

type CreateMembershipParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.OrganizationID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO membership_roles (membership_id, role)
VALUES ($1, $2)
`

type CreateRoleParams struct {
	MembershipID pgtype.UUID `json:"membership_id"`
	Role         string      `json:"role"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.Exec(ctx, createRole, arg.MembershipID, arg.Role)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (display_name, email, must_change_password)
VALUES ($1, $2, true)
RETURNING id
`

type CreateUserParams struct {
	DisplayName pgtype.Text `json:"display_name"`
	Email       pgtype.Text `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.DisplayName, arg.Email)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteOldPasswordHistory = `-- name: DeleteOldPasswordHistory :exec
DELETE FROM password_history
WHERE id IN (
    SELECT ph.id
    FROM password_history ph
    WHERE ph.user_id = $1
    ORDER BY ph.created_at DESC
    OFFSET $2
)
`

type DeleteOldPasswordHistoryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Offset int32       `json:"offset"`
}

func (q *Queries) DeleteOldPasswordHistory(ctx context.Context, arg DeleteOldPasswordHistoryParams) error {
	_, err := q.db.Exec(ctx, deleteOldPasswordHistory, arg.UserID, arg.Offset)
	return err
}

const deleteRoles = `-- name: DeleteRoles :exec
DELETE FROM membership_roles
WHERE membership_id = $1
`

func (q *Queries) DeleteRoles(ctx context.Context, membershipID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoles, membershipID)
	return err
}

const exportAuditLogs = `-- name: ExportAuditLogs :many
SELECT
    al.id,
    al.created_at,
    u.display_name AS actor_name,
    al.actor_user_id,
    al.action,
    al.resource_type,
    al.resource_id,
    al.before_json,
    al.after_json,
    al.metadata_json
FROM audit_logs al
LEFT JOIN users u ON u.id = al.actor_user_id
WHERE al.organization_id = $1
  AND ($2::text = '' OR al.action = $2)
  AND ($3::text = '' OR al.actor_user_id::text = $3)
  AND ($4::text = '' OR al.created_at >= $4::timestamptz)
  AND ($5::text = '' OR al.created_at <= $5::timestamptz)
ORDER BY al.created_at DESC, al.id DESC
`

type ExportAuditLogsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ActionName     string      `json:"action_name"`
	ActorUserID    string      `json:"actor_user_id"`
	FromTime       string      `json:"from_time"`
	ToTime         string      `json:"to_time"`
}

type ExportAuditLogsRow struct {
	ID           pgtype.UUID        `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ActorName    pgtype.Text        `json:"actor_name"`
	ActorUserID  pgtype.UUID        `json:"actor_user_id"`
	Action       string             `json:"action"`
	ResourceType pgtype.Text        `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	BeforeJson   []byte             `json:"before_json"`
	AfterJson    []byte             `json:"after_json"`
	MetadataJson []byte             `json:"metadata_json"`
}

func (q *Queries) ExportAuditLogs(ctx context.Context, arg ExportAuditLogsParams) ([]ExportAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, exportAuditLogs,
		arg.OrganizationID,
		arg.ActionName,
		arg.ActorUserID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportAuditLogsRow
	for rows.Next() {
		var i ExportAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorUserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoginPasswordHash = `-- name: GetLoginPasswordHash :one
SELECT password_hash
FROM membership_login_names
WHERE user_id = $1
  AND organization_id = $2
LIMIT 1
`

type GetLoginPasswordHashParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetLoginPasswordHash(ctx context.Context, arg GetLoginPasswordHashParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getLoginPasswordHash, arg.UserID, arg.OrganizationID)
	var password_hash pgtype.Text
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getMembershipID = `-- name: GetMembershipID :one
SELECT id
FROM organization_memberships
WHERE organization_id = $1
  AND user_id = $2
  AND status = 'ACTIVE'
LIMIT 1
`

type GetMembershipIDParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMembershipID(ctx context.Context, arg GetMembershipIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMembershipID, arg.OrganizationID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, code, name
FROM organizations
WHERE id = $1
LIMIT 1
`

type GetOrganizationRow struct {
	ID   pgtype.UUID `json:"id"`
	Code string      `json:"code"`
	Name string      `json:"name"`
}

func (q *Queries) GetOrganization(ctx context.Context, id pgtype.UUID) (GetOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i GetOrganizationRow
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (
    organization_id,
    actor_user_id,
    action,
    resource_type,
    resource_id,
    before_json,
    after_json,
    metadata_json
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditLogParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ActorUserID    pgtype.UUID `json:"actor_user_id"`
	Action         string      `json:"action"`
	ResourceType   pgtype.Text `json:"resource_type"`
	ResourceID     pgtype.UUID `json:"resource_id"`
	BeforeJson     []byte      `json:"before_json"`
	AfterJson      []byte      `json:"after_json"`
	MetadataJson   []byte      `json:"metadata_json"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.OrganizationID,
		arg.ActorUserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.BeforeJson,
		arg.AfterJson,
		arg.MetadataJson,
	)
	return err
}

const insertPasswordHistory = `-- name: InsertPasswordHistory :exec
INSERT INTO password_history (user_id, password_hash)
VALUES ($1, $2)
`

type InsertPasswordHistoryParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) InsertPasswordHistory(ctx context.Context, arg InsertPasswordHistoryParams) error {
	_, err := q.db.Exec(ctx, insertPasswordHistory, arg.UserID, arg.PasswordHash)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT
    id,
    actor_user_id,
    action,
    resource_type,
    resource_id,
    before_json,
    after_json,
    metadata_json,
    created_at
FROM audit_logs
WHERE organization_id = $1
  AND ($2::text = '' OR action = $2)
  AND ($3::text = '' OR actor_user_id::text = $3)
  AND ($4::text = '' OR created_at >= $4::timestamptz)
  AND ($5::text = '' OR created_at <= $5::timestamptz)
  AND ($6::text = '' OR created_at < $6::timestamptz OR (created_at = $6::timestamptz AND id::text < $7))
ORDER BY created_at DESC, id DESC
LIMIT NULLIF($9::int, 0) OFFSET $8::int
`

type ListAuditLogsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ActionName     string      `json:"action_name"`
	ActorUserID    string      `json:"actor_user_id"`
	FromTime       string      `json:"from_time"`
	ToTime         string      `json:"to_time"`
	CursorKey      string      `json:"cursor_key"`
	CursorID       pgtype.UUID `json:"cursor_id"`
	PageOffset     int32       `json:"page_offset"`
	PageLimit      int32       `json:"page_limit"`
}

type ListAuditLogsRow struct {
	ID           pgtype.UUID        `json:"id"`
	ActorUserID  pgtype.UUID        `json:"actor_user_id"`
	Action       string             `json:"action"`
	ResourceType pgtype.Text        `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	BeforeJson   []byte             `json:"before_json"`
	AfterJson    []byte             `json:"after_json"`
	MetadataJson []byte             `json:"metadata_json"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.OrganizationID,
		arg.ActionName,
		arg.ActorUserID,
		arg.FromTime,
		arg.ToTime,
		arg.CursorKey,
		arg.CursorID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsRow
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPasswordHistory = `-- name: ListPasswordHistory :many
SELECT password_hash
FROM password_history
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListPasswordHistoryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListPasswordHistory(ctx context.Context, arg ListPasswordHistoryParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPasswordHistory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var password_hash string
		if err := rows.Scan(&password_hash); err != nil {
			return nil, err
		}
		items = append(items, password_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT
    u.id,
    u.display_name,
    u.email,
    ln.username_normalized,
    u.must_change_password,
    array_agg(mr.role) FILTER (WHERE mr.role IS NOT NULL)
FROM users u
JOIN organization_memberships m ON m.user_id = u.id
JOIN membership_login_names ln ON ln.user_id = u.id AND ln.organization_id = m.organization_id
LEFT JOIN membership_roles mr ON mr.membership_id = m.id
WHERE m.organization_id = $1
  AND m.status = 'ACTIVE'
  AND ln.status = 'ACTIVE'
  AND ($2::text = '' OR ln.username_normalized ILIKE '%' || $2 || '%' OR u.display_name ILIKE '%' || $2 || '%' OR u.email ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR ln.username_normalized > $3 OR (ln.username_normalized = $3 AND u.id::text > $4))
GROUP BY u.id, u.display_name, u.email, ln.username_normalized, u.must_change_password
ORDER BY ln.username_normalized, u.id
LIMIT NULLIF($6::int, 0) OFFSET $5::int
`

type ListUsersParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	SearchQuery    string      `json:"search_query"`
	CursorKey      string      `json:"cursor_key"`
	CursorID       pgtype.UUID `json:"cursor_id"`
	PageOffset     int32       `json:"page_offset"`
	PageLimit      int32       `json:"page_limit"`
}

type ListUsersRow struct {
	ID                 pgtype.UUID `json:"id"`
	DisplayName        pgtype.Text `json:"display_name"`
	Email              pgtype.Text `json:"email"`
	UsernameNormalized string      `json:"username_normalized"`
	MustChangePassword bool        `json:"must_change_password"`
	ArrayAgg           interface{} `json:"array_agg"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.OrganizationID,
		arg.SearchQuery,
		arg.CursorKey,
		arg.CursorID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Email,
			&i.UsernameNormalized,
			&i.MustChangePassword,
			&i.ArrayAgg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loginExists = `-- name: LoginExists :one
SELECT EXISTS (
    SELECT 1
    FROM membership_login_names
    WHERE organization_id = $1
      AND lower(username_normalized) = lower($2)
)
`

type LoginExistsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Lower          string      `json:"lower"`
}

func (q *Queries) LoginExists(ctx context.Context, arg LoginExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, loginExists, arg.OrganizationID, arg.Lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const resetPassword = `-- name: ResetPassword :execrows
UPDATE membership_login_names
SET password_hash = $1
WHERE user_id = $2
  AND organization_id = $3
`

type ResetPasswordParams struct {
	PasswordHash   pgtype.Text `json:"password_hash"`
	UserID         pgtype.UUID `json:"user_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ResetPassword(ctx context.Context, arg ResetPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetPassword, arg.PasswordHash, arg.UserID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE refresh_sessions
SET revoked_at = now()
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const setMustChangePassword = `-- name: SetMustChangePassword :exec
UPDATE users
SET must_change_password = true,
    auth_version = auth_version + 1
WHERE id = $1
`

func (q *Queries) SetMustChangePassword(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setMustChangePassword, id)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :execrows
UPDATE organizations
SET name = $1
WHERE id = $2
`

type UpdateOrganizationParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrganization, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
