// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package gradebooksqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assessmentExists = `-- name: AssessmentExists :one
SELECT EXISTS (
    SELECT 1
    FROM assessments
    WHERE id = $1 AND organization_id = $2
)
`

type AssessmentExistsParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) AssessmentExists(ctx context.Context, arg AssessmentExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, assessmentExists, arg.ID, arg.OrganizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAssessmentResults = `-- name: GetAssessmentResults :one
SELECT
    COUNT(*) AS total_attempts,
    COUNT(*) FILTER (WHERE status = 'SUBMITTED') AS submitted_count,
    COUNT(*) FILTER (WHERE status = 'IN_PROGRESS') AS in_progress_count,
    COUNT(*) FILTER (WHERE status = 'EXPIRED') AS expired_count,
    CASE WHEN COUNT(*) = 0 OR AVG(score) IS NULL THEN ''::text ELSE AVG(score)::text END AS average_score,
    CASE WHEN COUNT(*) = 0 OR MAX(max_score) IS NULL THEN ''::text ELSE MAX(max_score)::text END AS max_score
FROM attempts
WHERE organization_id = $1
  AND assessment_id = $2
`

type GetAssessmentResultsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
}

type GetAssessmentResultsRow struct {
	TotalAttempts   int64  `json:"total_attempts"`
	SubmittedCount  int64  `json:"submitted_count"`
	InProgressCount int64  `json:"in_progress_count"`
	ExpiredCount    int64  `json:"expired_count"`
	AverageScore    string `json:"average_score"`
	MaxScore        string `json:"max_score"`
}

func (q *Queries) GetAssessmentResults(ctx context.Context, arg GetAssessmentResultsParams) (GetAssessmentResultsRow, error) {
	row := q.db.QueryRow(ctx, getAssessmentResults, arg.OrganizationID, arg.AssessmentID)
	var i GetAssessmentResultsRow
	err := row.Scan(
		&i.TotalAttempts,
		&i.SubmittedCount,
		&i.InProgressCount,
		&i.ExpiredCount,
		&i.AverageScore,
		&i.MaxScore,
	)
	return i, err
}

const getClassGradebook = `-- name: GetClassGradebook :many
SELECT
    u.id AS student_user_id,
    u.display_name AS student_name,
    a.id AS assessment_id,
    a.title AS assessment_title,
    att.id AS attempt_id,
    att.status,
    CASE WHEN att.score IS NULL THEN ''::text ELSE att.score::text END AS score,
    CASE WHEN att.max_score IS NULL THEN ''::text ELSE att.max_score::text END AS max_score,
    att.submitted_at
FROM class_sections cs
JOIN enrollments e
    ON e.class_section_id = cs.id
    AND e.status = 'ACTIVE'
JOIN organization_memberships m
    ON m.id = e.membership_id
    AND m.organization_id = cs.organization_id
    AND m.status = 'ACTIVE'
JOIN users u
    ON u.id = m.user_id
JOIN assessment_targets t
    ON t.class_section_id = cs.id
    AND t.status = 'ACTIVE'
JOIN assessments a
    ON a.id = t.assessment_id
    AND a.organization_id = cs.organization_id
    AND a.status IN ('OPEN', 'PUBLISHED')
LEFT JOIN LATERAL (
    SELECT att.id, att.status, att.score, att.max_score, att.submitted_at
    FROM attempts att
    WHERE att.organization_id = cs.organization_id
      AND att.assessment_id = a.id
      AND att.student_user_id = u.id
    ORDER BY att.created_at DESC, att.started_at DESC
    LIMIT 1
) att ON true
WHERE cs.organization_id = $1
  AND cs.id = $2
ORDER BY u.display_name, a.title
`

type GetClassGradebookParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ID             pgtype.UUID `json:"id"`
}

type GetClassGradebookRow struct {
	StudentUserID   pgtype.UUID        `json:"student_user_id"`
	StudentName     pgtype.Text        `json:"student_name"`
	AssessmentID    pgtype.UUID        `json:"assessment_id"`
	AssessmentTitle string             `json:"assessment_title"`
	AttemptID       pgtype.UUID        `json:"attempt_id"`
	Status          string             `json:"status"`
	Score           string             `json:"score"`
	MaxScore        string             `json:"max_score"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
}

func (q *Queries) GetClassGradebook(ctx context.Context, arg GetClassGradebookParams) ([]GetClassGradebookRow, error) {
	rows, err := q.db.Query(ctx, getClassGradebook, arg.OrganizationID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClassGradebookRow
	for rows.Next() {
		var i GetClassGradebookRow
		if err := rows.Scan(
			&i.StudentUserID,
			&i.StudentName,
			&i.AssessmentID,
			&i.AssessmentTitle,
			&i.AttemptID,
			&i.Status,
			&i.Score,
			&i.MaxScore,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isAssessmentTaughtByTeacher = `-- name: IsAssessmentTaughtByTeacher :one
SELECT EXISTS (
    SELECT 1
    FROM assessment_targets t
    JOIN class_teachers ct
        ON ct.class_section_id = t.class_section_id
        AND ct.organization_id = t.organization_id
        AND ct.status = 'ACTIVE'
    JOIN organization_memberships m
        ON m.id = ct.membership_id
        AND m.organization_id = t.organization_id
        AND m.status = 'ACTIVE'
    WHERE t.organization_id = $1
      AND t.assessment_id = $2
      AND t.status = 'ACTIVE'
      AND m.user_id = $3
)
`

type IsAssessmentTaughtByTeacherParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsAssessmentTaughtByTeacher(ctx context.Context, arg IsAssessmentTaughtByTeacherParams) (bool, error) {
	row := q.db.QueryRow(ctx, isAssessmentTaughtByTeacher, arg.OrganizationID, arg.AssessmentID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAssessmentAttempts = `-- name: ListAssessmentAttempts :many
SELECT
    a.id,
    a.assessment_id,
    a.student_user_id,
    u.display_name AS student_name,
    a.status,
    a.started_at,
    a.expires_at,
    a.submitted_at,
    CASE WHEN a.score IS NULL THEN ''::text ELSE a.score::text END AS score,
    CASE WHEN a.max_score IS NULL THEN ''::text ELSE a.max_score::text END AS max_score,
    a.grading_status
FROM attempts a
JOIN users u ON u.id = a.student_user_id
WHERE a.organization_id = $1
  AND a.assessment_id = $2
ORDER BY a.created_at DESC, a.started_at DESC
`

type ListAssessmentAttemptsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
}

type ListAssessmentAttemptsRow struct {
	ID            pgtype.UUID        `json:"id"`
	AssessmentID  pgtype.UUID        `json:"assessment_id"`
	StudentUserID pgtype.UUID        `json:"student_user_id"`
	StudentName   pgtype.Text        `json:"student_name"`
	Status        string             `json:"status"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	Score         string             `json:"score"`
	MaxScore      string             `json:"max_score"`
	GradingStatus pgtype.Text        `json:"grading_status"`
}

func (q *Queries) ListAssessmentAttempts(ctx context.Context, arg ListAssessmentAttemptsParams) ([]ListAssessmentAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listAssessmentAttempts, arg.OrganizationID, arg.AssessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssessmentAttemptsRow
	for rows.Next() {
		var i ListAssessmentAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.StudentUserID,
			&i.StudentName,
			&i.Status,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.SubmittedAt,
			&i.Score,
			&i.MaxScore,
			&i.GradingStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
