/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/csrf-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth.csrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requires `vts_refresh` HttpOnly cookie and `X-CSRF-Token` header. */
        post: operations["auth.refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requires `vts_refresh` HttpOnly cookie and `X-CSRF-Token` header. */
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requires Bearer access token and `X-CSRF-Token` header. Enforces password policy and rejects recently used passwords. */
        post: operations["auth.changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{attempt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["attempts.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{attempt_id}/answers/{attempt_item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Requires Bearer access token and `X-CSRF-Token` header. */
        put: operations["attempts.saveAnswer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{attempt_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requires Bearer access token and `X-CSRF-Token` header. */
        post: operations["attempts.submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Teacher or admin only. Optional case-insensitive title search and pagination. */
        get: operations["assessments.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin only. Optional case-insensitive search on login name, display name, or email, plus pagination. */
        get: operations["users.list"];
        put?: never;
        /** @description Admin only. Requires `X-CSRF-Token` header. */
        post: operations["users.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Admin only. Requires `X-CSRF-Token` header. */
        put: operations["users.updateRoles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Admin only. Requires `X-CSRF-Token` header. */
        post: operations["users.resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin only. */
        get: operations["organizations.getCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Admin only. Requires `X-CSRF-Token` header. */
        patch: operations["organizations.updateCurrent"];
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin only. List audit logs for the current organization, optionally filtered. */
        get: operations["auditLogs.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CsrfTokenResponse: {
            data: {
                csrf_token: string;
            };
        };
        LoginRequest: {
            organization_code: string;
            username: string;
            password: string;
        };
        LoginResponse: {
            data: {
                access_token: string;
                expires_in: number;
                user: {
                    /** Format: uuid */
                    id: string;
                    display_name: string;
                };
                roles: string[];
                permissions: string[];
                must_change_password: boolean;
            };
        };
        SuccessResponse: {
            data: {
                success: boolean;
            };
        };
        ChangePasswordRequest: {
            current_password: string;
            /** @description Must contain at least one uppercase letter, one lowercase letter, one digit, and not match a common blocklist. */
            new_password: string;
        };
        MeResponse: {
            data: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                organization_id: string;
                display_name: string;
                roles: string[];
                permissions: string[];
                must_change_password: boolean;
            };
        };
        AttemptSnapshot: {
            data: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                organization_id: string;
                /** Format: uuid */
                assessment_id: string;
                /** Format: uuid */
                publication_id?: string | null;
                /** @enum {string} */
                status: "CREATED" | "IN_PROGRESS" | "SUBMITTED" | "EXPIRED" | "TERMINATED";
                /** Format: date-time */
                started_at?: string | null;
                /** Format: date-time */
                expires_at?: string | null;
                /** Format: date-time */
                submitted_at?: string | null;
                items: components["schemas"]["AttemptItem"][];
            };
        };
        AttemptItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            question_version_id: string;
            position: number;
            points: string;
            prompt: {
                text?: string;
            } & {
                [key: string]: unknown;
            };
            choices: ({
                id?: string;
                text?: string;
            } & {
                [key: string]: unknown;
            })[];
            answer?: {
                answer_payload: {
                    selected_option?: string;
                } & {
                    [key: string]: unknown;
                };
                revision: number;
                /** Format: date-time */
                answered_at: string;
            };
        };
        SaveAnswerRequest: {
            answer_payload: {
                selected_option?: string;
            } & {
                [key: string]: unknown;
            };
        };
        SaveAnswerResponse: {
            data: {
                /** Format: uuid */
                attempt_item_id: string;
                revision: number;
                answer_payload: {
                    selected_option?: string;
                } & {
                    [key: string]: unknown;
                };
                /** Format: date-time */
                answered_at: string;
            };
        };
        AttemptSubmitted: {
            data: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                status: "SUBMITTED" | "EXPIRED";
                /** Format: date-time */
                submitted_at: string;
                score: string;
                max_score: string;
                /** @enum {string} */
                grading_status: "GRADED";
            };
        };
        PageInfo: {
            limit: number;
            offset: number;
            next_cursor?: string;
            has_more: boolean;
            total_count?: number;
        };
        AssessmentList: {
            data: components["schemas"]["AssessmentListItem"][];
            page?: components["schemas"]["PageInfo"];
        };
        AssessmentListItem: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @enum {string} */
            status: "OPEN" | "PUBLISHED";
            duration_minutes: number;
        };
        UserList: {
            data: components["schemas"]["User"][];
            page?: components["schemas"]["PageInfo"];
        };
        User: {
            /** Format: uuid */
            id: string;
            display_name: string;
            email: string | null;
            login_name: string;
            roles: string[];
            must_change_password: boolean;
        };
        CreateUserRequest: {
            login_name: string;
            display_name: string;
            email?: string | null;
            /** @description Must contain at least one uppercase letter, one lowercase letter, one digit, and not match a common blocklist. */
            temporary_password: string;
            roles: ("student" | "teacher" | "admin")[];
        };
        UpdateRolesRequest: {
            roles: ("student" | "teacher" | "admin")[];
        };
        ResetPasswordRequest: {
            /** @description Must contain at least one uppercase letter, one lowercase letter, one digit, and not match a common blocklist. */
            temporary_password: string;
        };
        AuditLogList: {
            data: components["schemas"]["AuditLog"][];
            page?: components["schemas"]["PageInfo"];
        };
        AuditLog: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            actor_user_id: string;
            action: string;
            resource_type: string;
            /** Format: uuid */
            resource_id: string;
            before?: {
                [key: string]: unknown;
            };
            after?: {
                [key: string]: unknown;
            };
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        Organization: {
            data: {
                /** Format: uuid */
                id: string;
                code: string;
                name: string;
            };
        };
        UpdateOrganizationRequest: {
            name: string;
        };
        Problem: {
            /** Format: uri-reference */
            type?: string;
            title: string;
            status: number;
            code: string;
            detail?: string;
            request_id?: string;
        };
    };
    responses: {
        /** @description Authentication required or invalid */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Insufficient permissions or invalid CSRF token */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Invalid request body */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource conflict or attempt not in progress/expired */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit or temporary account lockout exceeded */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Case-insensitive search query. */
        ListQuery: string;
        /** @description Page size. When omitted the full list is returned. */
        ListLimit: number;
        /** @description Number of rows to skip. */
        ListOffset: number;
        /** @description Opaque cursor for the next page. Resets offset to 0. */
        ListCursor: string;
        /** @description When true, include total_count in the page metadata. */
        ListCount: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth.csrfToken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token returned and set as cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfTokenResponse"];
                };
            };
        };
    };
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login success; refresh cookie set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    "auth.refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Access token refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout success; refresh cookie cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    "auth.changePassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed; all refresh sessions revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    "me.get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current actor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    "attempts.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attempt snapshot with item prompts and choices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptSnapshot"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    "attempts.saveAnswer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
                attempt_item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveAnswerRequest"];
            };
        };
        responses: {
            /** @description Answer saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveAnswerResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    "attempts.submit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submitted and graded (MCQ) or expired */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptSubmitted"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    "assessments.list": {
        parameters: {
            query?: {
                /** @description Case-insensitive search query. */
                q?: components["parameters"]["ListQuery"];
                /** @description Page size. When omitted the full list is returned. */
                limit?: components["parameters"]["ListLimit"];
                /** @description Number of rows to skip. */
                offset?: components["parameters"]["ListOffset"];
                /** @description Opaque cursor for the next page. Resets offset to 0. */
                cursor?: components["parameters"]["ListCursor"];
                /** @description When true, include total_count in the page metadata. */
                count?: components["parameters"]["ListCount"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published/open assessments for the current organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    "users.list": {
        parameters: {
            query?: {
                /** @description Case-insensitive search query. */
                q?: components["parameters"]["ListQuery"];
                /** @description Page size. When omitted the full list is returned. */
                limit?: components["parameters"]["ListLimit"];
                /** @description Number of rows to skip. */
                offset?: components["parameters"]["ListOffset"];
                /** @description Opaque cursor for the next page. Resets offset to 0. */
                cursor?: components["parameters"]["ListCursor"];
                /** @description When true, include total_count in the page metadata. */
                count?: components["parameters"]["ListCount"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users in the current organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    "users.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    "users.updateRoles": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRolesRequest"];
            };
        };
        responses: {
            /** @description Roles updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    "users.resetPassword": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password reset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    "organizations.getCurrent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    "organizations.updateCurrent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationRequest"];
            };
        };
        responses: {
            /** @description Organization updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    "auditLogs.list": {
        parameters: {
            query?: {
                /** @description Filter by action name. */
                action?: string;
                /** @description Filter by actor user ID. */
                actor_user_id?: string;
                /** @description Start timestamp (RFC3339). */
                from?: string;
                /** @description End timestamp (RFC3339). */
                to?: string;
                /** @description Page size. When omitted the full list is returned. */
                limit?: components["parameters"]["ListLimit"];
                /** @description Number of rows to skip. */
                offset?: components["parameters"]["ListOffset"];
                /** @description Opaque cursor for the next page. Resets offset to 0. */
                cursor?: components["parameters"]["ListCursor"];
                /** @description When true, include total_count in the page metadata. */
                count?: components["parameters"]["ListCount"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit logs for the current organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
