// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Assessment struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	ClassSectionID  pgtype.UUID        `json:"class_section_id"`
	Title           string             `json:"title"`
	DurationMinutes int32              `json:"duration_minutes"`
	MaxAttempts     int32              `json:"max_attempts"`
	SettingsJson    []byte             `json:"settings_json"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AssessmentPublication struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AssessmentID   pgtype.UUID        `json:"assessment_id"`
	Version        int32              `json:"version"`
	SnapshotJson   []byte             `json:"snapshot_json"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Attempt struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AssessmentID   pgtype.UUID        `json:"assessment_id"`
	StudentUserID  pgtype.UUID        `json:"student_user_id"`
	PublicationID  pgtype.UUID        `json:"publication_id"`
	Status         string             `json:"status"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Score          pgtype.Numeric     `json:"score"`
	MaxScore       pgtype.Numeric     `json:"max_score"`
	GradingStatus  pgtype.Text        `json:"grading_status"`
}

type AttemptAnswer struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AttemptID      pgtype.UUID        `json:"attempt_id"`
	AttemptItemID  pgtype.UUID        `json:"attempt_item_id"`
	AnswerPayload  []byte             `json:"answer_payload"`
	Revision       int64              `json:"revision"`
	AnsweredAt     pgtype.Timestamptz `json:"answered_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AttemptItem struct {
	ID                pgtype.UUID        `json:"id"`
	OrganizationID    pgtype.UUID        `json:"organization_id"`
	AttemptID         pgtype.UUID        `json:"attempt_id"`
	QuestionVersionID pgtype.UUID        `json:"question_version_id"`
	Position          int32              `json:"position"`
	Points            pgtype.Numeric     `json:"points"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	AnswerKeyJson     []byte             `json:"answer_key_json"`
	PromptJson        []byte             `json:"prompt_json"`
	ChoicesJson       []byte             `json:"choices_json"`
}

type AuditLog struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	ActorUserID    pgtype.UUID        `json:"actor_user_id"`
	ActorType      pgtype.Text        `json:"actor_type"`
	Action         string             `json:"action"`
	ResourceType   pgtype.Text        `json:"resource_type"`
	ResourceID     pgtype.UUID        `json:"resource_id"`
	RequestID      pgtype.Text        `json:"request_id"`
	IpPrefixOrHash pgtype.Text        `json:"ip_prefix_or_hash"`
	UserAgentHash  pgtype.Text        `json:"user_agent_hash"`
	BeforeJson     []byte             `json:"before_json"`
	AfterJson      []byte             `json:"after_json"`
	MetadataJson   []byte             `json:"metadata_json"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type IdempotencyKey struct {
	ID               pgtype.UUID        `json:"id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	ActorUserID      pgtype.UUID        `json:"actor_user_id"`
	Scope            string             `json:"scope"`
	KeyHash          string             `json:"key_hash"`
	RequestHash      pgtype.Text        `json:"request_hash"`
	ResponseStatus   pgtype.Int4        `json:"response_status"`
	ResponseBodyJson []byte             `json:"response_body_json"`
	ResourceID       pgtype.UUID        `json:"resource_id"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type LoginAttempt struct {
	ID                 pgtype.UUID        `json:"id"`
	OrganizationID     pgtype.UUID        `json:"organization_id"`
	UsernameNormalized string             `json:"username_normalized"`
	AttemptedAt        pgtype.Timestamptz `json:"attempted_at"`
}

type MembershipLoginName struct {
	ID                 pgtype.UUID        `json:"id"`
	OrganizationID     pgtype.UUID        `json:"organization_id"`
	UsernameNormalized string             `json:"username_normalized"`
	UserID             pgtype.UUID        `json:"user_id"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	PasswordHash       pgtype.Text        `json:"password_hash"`
}

type MembershipRole struct {
	MembershipID pgtype.UUID        `json:"membership_id"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationMembership struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PasswordHistory struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Question struct {
	ID             pgtype.UUID        `json:"id"`
	QuestionBankID pgtype.UUID        `json:"question_bank_id"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type QuestionBank struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type QuestionVersion struct {
	ID            pgtype.UUID        `json:"id"`
	QuestionID    pgtype.UUID        `json:"question_id"`
	Version       int32              `json:"version"`
	PromptJson    []byte             `json:"prompt_json"`
	ChoicesJson   []byte             `json:"choices_json"`
	AnswerKeyJson []byte             `json:"answer_key_json"`
	MaxScore      pgtype.Numeric     `json:"max_score"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type RefreshSession struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	MembershipID        pgtype.UUID        `json:"membership_id"`
	OrganizationID      pgtype.UUID        `json:"organization_id"`
	TokenHash           string             `json:"token_hash"`
	FamilyID            pgtype.UUID        `json:"family_id"`
	AuthVersion         int64              `json:"auth_version"`
	DeviceMetadataJson  []byte             `json:"device_metadata_json"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ReplacedByTokenHash pgtype.Text        `json:"replaced_by_token_hash"`
}

type User struct {
	ID                 pgtype.UUID        `json:"id"`
	EmailNormalized    pgtype.Text        `json:"email_normalized"`
	Status             string             `json:"status"`
	AuthVersion        int64              `json:"auth_version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	MustChangePassword bool               `json:"must_change_password"`
	Email              pgtype.Text        `json:"email"`
	DisplayName        pgtype.Text        `json:"display_name"`
}
