// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package authsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpUserAuthVersion = `-- name: BumpUserAuthVersion :exec
UPDATE users
SET auth_version = auth_version + 1,
    must_change_password = false
WHERE id = $1
`

func (q *Queries) BumpUserAuthVersion(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bumpUserAuthVersion, id)
	return err
}

const clearLoginAttempts = `-- name: ClearLoginAttempts :exec
DELETE FROM login_attempts
WHERE organization_id = $1
  AND username_normalized = lower($2)
`

type ClearLoginAttemptsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Lower          string      `json:"lower"`
}

func (q *Queries) ClearLoginAttempts(ctx context.Context, arg ClearLoginAttemptsParams) error {
	_, err := q.db.Exec(ctx, clearLoginAttempts, arg.OrganizationID, arg.Lower)
	return err
}

const countFailedLoginAttempts = `-- name: CountFailedLoginAttempts :one
SELECT COUNT(*)
FROM login_attempts
WHERE organization_id = $1
  AND username_normalized = lower($2)
  AND attempted_at >= now() - $3::interval
`

type CountFailedLoginAttemptsParams struct {
	OrganizationID pgtype.UUID     `json:"organization_id"`
	Lower          string          `json:"lower"`
	Column3        pgtype.Interval `json:"column_3"`
}

func (q *Queries) CountFailedLoginAttempts(ctx context.Context, arg CountFailedLoginAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFailedLoginAttempts, arg.OrganizationID, arg.Lower, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldPasswordHistory = `-- name: DeleteOldPasswordHistory :exec
DELETE FROM password_history
WHERE id IN (
    SELECT ph.id
    FROM password_history ph
    WHERE ph.user_id = $1
    ORDER BY ph.created_at DESC
    OFFSET $2
)
`

type DeleteOldPasswordHistoryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Offset int32       `json:"offset"`
}

func (q *Queries) DeleteOldPasswordHistory(ctx context.Context, arg DeleteOldPasswordHistoryParams) error {
	_, err := q.db.Exec(ctx, deleteOldPasswordHistory, arg.UserID, arg.Offset)
	return err
}

const findLoginByCredentials = `-- name: FindLoginByCredentials :one
SELECT
    u.id,
    m.id,
    o.id,
    ln.username_normalized,
    ln.password_hash,
    u.auth_version,
    u.must_change_password,
    array_agg(mr.role) FILTER (WHERE mr.role IS NOT NULL)
FROM membership_login_names ln
JOIN organizations o ON o.id = ln.organization_id
JOIN organization_memberships m
    ON m.organization_id = ln.organization_id AND m.user_id = ln.user_id
JOIN users u ON u.id = ln.user_id
LEFT JOIN membership_roles mr ON mr.membership_id = m.id
WHERE lower(o.code) = lower($1)
  AND lower(ln.username_normalized) = lower($2)
  AND o.status = 'ACTIVE'
  AND m.status = 'ACTIVE'
  AND ln.status = 'ACTIVE'
GROUP BY u.id, m.id, o.id, ln.username_normalized, ln.password_hash, u.auth_version, u.must_change_password
LIMIT 1
`

type FindLoginByCredentialsParams struct {
	Lower   string `json:"lower"`
	Lower_2 string `json:"lower_2"`
}

type FindLoginByCredentialsRow struct {
	ID                 pgtype.UUID `json:"id"`
	ID_2               pgtype.UUID `json:"id_2"`
	ID_3               pgtype.UUID `json:"id_3"`
	UsernameNormalized string      `json:"username_normalized"`
	PasswordHash       pgtype.Text `json:"password_hash"`
	AuthVersion        int64       `json:"auth_version"`
	MustChangePassword bool        `json:"must_change_password"`
	ArrayAgg           interface{} `json:"array_agg"`
}

func (q *Queries) FindLoginByCredentials(ctx context.Context, arg FindLoginByCredentialsParams) (FindLoginByCredentialsRow, error) {
	row := q.db.QueryRow(ctx, findLoginByCredentials, arg.Lower, arg.Lower_2)
	var i FindLoginByCredentialsRow
	err := row.Scan(
		&i.ID,
		&i.ID_2,
		&i.ID_3,
		&i.UsernameNormalized,
		&i.PasswordHash,
		&i.AuthVersion,
		&i.MustChangePassword,
		&i.ArrayAgg,
	)
	return i, err
}

const findRefreshSessionByTokenHash = `-- name: FindRefreshSessionByTokenHash :one
SELECT
    id,
    user_id,
    membership_id,
    organization_id,
    family_id,
    auth_version,
    expires_at,
    revoked_at,
    replaced_by_token_hash
FROM refresh_sessions
WHERE token_hash = $1
LIMIT 1
`

type FindRefreshSessionByTokenHashRow struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	MembershipID        pgtype.UUID        `json:"membership_id"`
	OrganizationID      pgtype.UUID        `json:"organization_id"`
	FamilyID            pgtype.UUID        `json:"family_id"`
	AuthVersion         int64              `json:"auth_version"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	ReplacedByTokenHash pgtype.Text        `json:"replaced_by_token_hash"`
}

func (q *Queries) FindRefreshSessionByTokenHash(ctx context.Context, tokenHash string) (FindRefreshSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, findRefreshSessionByTokenHash, tokenHash)
	var i FindRefreshSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MembershipID,
		&i.OrganizationID,
		&i.FamilyID,
		&i.AuthVersion,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByTokenHash,
	)
	return i, err
}

const getActorByUserID = `-- name: GetActorByUserID :one
SELECT ln.user_id, ln.organization_id, ln.username_normalized, u.must_change_password
FROM membership_login_names ln
JOIN users u ON u.id = ln.user_id
WHERE ln.user_id = $1
  AND ln.organization_id = $2
  AND ln.status = 'ACTIVE'
LIMIT 1
`

type GetActorByUserIDParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetActorByUserIDRow struct {
	UserID             pgtype.UUID `json:"user_id"`
	OrganizationID     pgtype.UUID `json:"organization_id"`
	UsernameNormalized string      `json:"username_normalized"`
	MustChangePassword bool        `json:"must_change_password"`
}

func (q *Queries) GetActorByUserID(ctx context.Context, arg GetActorByUserIDParams) (GetActorByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getActorByUserID, arg.UserID, arg.OrganizationID)
	var i GetActorByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.OrganizationID,
		&i.UsernameNormalized,
		&i.MustChangePassword,
	)
	return i, err
}

const getLoginByUserID = `-- name: GetLoginByUserID :one
SELECT
    u.id,
    m.id,
    o.id,
    ln.username_normalized,
    ln.password_hash,
    u.auth_version,
    u.must_change_password,
    array_agg(mr.role) FILTER (WHERE mr.role IS NOT NULL)
FROM membership_login_names ln
JOIN organizations o ON o.id = ln.organization_id
JOIN organization_memberships m
    ON m.organization_id = ln.organization_id AND m.user_id = ln.user_id
JOIN users u ON u.id = ln.user_id
LEFT JOIN membership_roles mr ON mr.membership_id = m.id
WHERE u.id = $1
  AND o.id = $2
  AND o.status = 'ACTIVE'
  AND m.status = 'ACTIVE'
  AND ln.status = 'ACTIVE'
GROUP BY u.id, m.id, o.id, ln.username_normalized, ln.password_hash, u.auth_version, u.must_change_password
LIMIT 1
`

type GetLoginByUserIDParams struct {
	ID   pgtype.UUID `json:"id"`
	ID_2 pgtype.UUID `json:"id_2"`
}

type GetLoginByUserIDRow struct {
	ID                 pgtype.UUID `json:"id"`
	ID_2               pgtype.UUID `json:"id_2"`
	ID_3               pgtype.UUID `json:"id_3"`
	UsernameNormalized string      `json:"username_normalized"`
	PasswordHash       pgtype.Text `json:"password_hash"`
	AuthVersion        int64       `json:"auth_version"`
	MustChangePassword bool        `json:"must_change_password"`
	ArrayAgg           interface{} `json:"array_agg"`
}

func (q *Queries) GetLoginByUserID(ctx context.Context, arg GetLoginByUserIDParams) (GetLoginByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getLoginByUserID, arg.ID, arg.ID_2)
	var i GetLoginByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.ID_2,
		&i.ID_3,
		&i.UsernameNormalized,
		&i.PasswordHash,
		&i.AuthVersion,
		&i.MustChangePassword,
		&i.ArrayAgg,
	)
	return i, err
}

const getRefreshSessionWithContext = `-- name: GetRefreshSessionWithContext :one
SELECT
    rs.id,
    rs.user_id,
    rs.membership_id,
    rs.organization_id,
    rs.family_id,
    rs.auth_version,
    rs.expires_at,
    rs.revoked_at,
    rs.replaced_by_token_hash
FROM refresh_sessions rs
JOIN organizations o ON o.id = rs.organization_id
JOIN organization_memberships m ON m.id = rs.membership_id
JOIN users u ON u.id = rs.user_id
WHERE rs.token_hash = $1
  AND o.status = 'ACTIVE'
  AND m.status = 'ACTIVE'
  AND u.status = 'ACTIVE'
  AND u.auth_version = rs.auth_version
FOR UPDATE
`

type GetRefreshSessionWithContextRow struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	MembershipID        pgtype.UUID        `json:"membership_id"`
	OrganizationID      pgtype.UUID        `json:"organization_id"`
	FamilyID            pgtype.UUID        `json:"family_id"`
	AuthVersion         int64              `json:"auth_version"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	ReplacedByTokenHash pgtype.Text        `json:"replaced_by_token_hash"`
}

func (q *Queries) GetRefreshSessionWithContext(ctx context.Context, tokenHash string) (GetRefreshSessionWithContextRow, error) {
	row := q.db.QueryRow(ctx, getRefreshSessionWithContext, tokenHash)
	var i GetRefreshSessionWithContextRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MembershipID,
		&i.OrganizationID,
		&i.FamilyID,
		&i.AuthVersion,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByTokenHash,
	)
	return i, err
}

const getRolesByMembershipID = `-- name: GetRolesByMembershipID :many
SELECT role
FROM membership_roles
WHERE membership_id = $1
ORDER BY role
`

func (q *Queries) GetRolesByMembershipID(ctx context.Context, membershipID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getRolesByMembershipID, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFailedLoginAttempt = `-- name: InsertFailedLoginAttempt :exec
INSERT INTO login_attempts (organization_id, username_normalized)
VALUES ($1, lower($2))
`

type InsertFailedLoginAttemptParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Lower          string      `json:"lower"`
}

func (q *Queries) InsertFailedLoginAttempt(ctx context.Context, arg InsertFailedLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, insertFailedLoginAttempt, arg.OrganizationID, arg.Lower)
	return err
}

const insertPasswordHistory = `-- name: InsertPasswordHistory :exec
INSERT INTO password_history (user_id, password_hash)
VALUES ($1, $2)
`

type InsertPasswordHistoryParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) InsertPasswordHistory(ctx context.Context, arg InsertPasswordHistoryParams) error {
	_, err := q.db.Exec(ctx, insertPasswordHistory, arg.UserID, arg.PasswordHash)
	return err
}

const insertRefreshSession = `-- name: InsertRefreshSession :one
INSERT INTO refresh_sessions (
    user_id,
    membership_id,
    organization_id,
    token_hash,
    family_id,
    auth_version,
    device_metadata_json,
    expires_at
) VALUES ($1, $2, $3, $4, $5, $6, '{}', $7)
RETURNING id
`

type InsertRefreshSessionParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	MembershipID   pgtype.UUID        `json:"membership_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	TokenHash      string             `json:"token_hash"`
	FamilyID       pgtype.UUID        `json:"family_id"`
	AuthVersion    int64              `json:"auth_version"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertRefreshSession(ctx context.Context, arg InsertRefreshSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertRefreshSession,
		arg.UserID,
		arg.MembershipID,
		arg.OrganizationID,
		arg.TokenHash,
		arg.FamilyID,
		arg.AuthVersion,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listPasswordHistory = `-- name: ListPasswordHistory :many
SELECT password_hash
FROM password_history
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListPasswordHistoryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListPasswordHistory(ctx context.Context, arg ListPasswordHistoryParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPasswordHistory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var password_hash string
		if err := rows.Scan(&password_hash); err != nil {
			return nil, err
		}
		items = append(items, password_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionReplaced = `-- name: MarkSessionReplaced :exec
UPDATE refresh_sessions
SET replaced_by_token_hash = $2
WHERE id = $1
`

type MarkSessionReplacedParams struct {
	ID                  pgtype.UUID `json:"id"`
	ReplacedByTokenHash pgtype.Text `json:"replaced_by_token_hash"`
}

func (q *Queries) MarkSessionReplaced(ctx context.Context, arg MarkSessionReplacedParams) error {
	_, err := q.db.Exec(ctx, markSessionReplaced, arg.ID, arg.ReplacedByTokenHash)
	return err
}

const revokeFamily = `-- name: RevokeFamily :exec
UPDATE refresh_sessions
SET revoked_at = now()
WHERE family_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeFamily(ctx context.Context, familyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeFamily, familyID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE refresh_sessions
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE refresh_sessions
SET revoked_at = now()
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const updateLoginPassword = `-- name: UpdateLoginPassword :execrows
UPDATE membership_login_names
SET password_hash = $1
WHERE user_id = $2
  AND organization_id = $3
`

type UpdateLoginPasswordParams struct {
	PasswordHash   pgtype.Text `json:"password_hash"`
	UserID         pgtype.UUID `json:"user_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) UpdateLoginPassword(ctx context.Context, arg UpdateLoginPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLoginPassword, arg.PasswordHash, arg.UserID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
