// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package academicssqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addClassTeacher = `-- name: AddClassTeacher :one
WITH inserted AS (
    INSERT INTO class_teachers (organization_id, class_section_id, membership_id, role)
    VALUES ($1, $2, $3, $4)
    RETURNING id, membership_id, role, status
)
SELECT inserted.id, u.id AS user_id, u.display_name, inserted.role, inserted.status
FROM inserted
JOIN organization_memberships m ON m.id = inserted.membership_id
JOIN users u ON u.id = m.user_id
`

type AddClassTeacherParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ClassSectionID pgtype.UUID `json:"class_section_id"`
	MembershipID   pgtype.UUID `json:"membership_id"`
	Role           string      `json:"role"`
}

type AddClassTeacherRow struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	DisplayName pgtype.Text `json:"display_name"`
	Role        string      `json:"role"`
	Status      string      `json:"status"`
}

func (q *Queries) AddClassTeacher(ctx context.Context, arg AddClassTeacherParams) (AddClassTeacherRow, error) {
	row := q.db.QueryRow(ctx, addClassTeacher,
		arg.OrganizationID,
		arg.ClassSectionID,
		arg.MembershipID,
		arg.Role,
	)
	var i AddClassTeacherRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const archiveClass = `-- name: ArchiveClass :execrows
UPDATE class_sections
SET status = 'ARCHIVED',
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND status = 'ACTIVE'
`

type ArchiveClassParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ArchiveClass(ctx context.Context, arg ArchiveClassParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveClass, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const archiveCourse = `-- name: ArchiveCourse :execrows
UPDATE courses
SET status = 'ARCHIVED',
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND status = 'ACTIVE'
`

type ArchiveCourseParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ArchiveCourse(ctx context.Context, arg ArchiveCourseParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveCourse, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const archiveSubject = `-- name: ArchiveSubject :execrows
UPDATE subjects
SET status = 'ARCHIVED',
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND status = 'ACTIVE'
`

type ArchiveSubjectParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ArchiveSubject(ctx context.Context, arg ArchiveSubjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveSubject, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const archiveTerm = `-- name: ArchiveTerm :execrows
UPDATE academic_terms
SET status = 'ARCHIVED',
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND status = 'ACTIVE'
`

type ArchiveTermParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ArchiveTerm(ctx context.Context, arg ArchiveTermParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveTerm, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const classExists = `-- name: ClassExists :one
SELECT EXISTS (
    SELECT 1
    FROM class_sections
    WHERE organization_id = $1
      AND id = $2
      AND status = 'ACTIVE'
)
`

type ClassExistsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) ClassExists(ctx context.Context, arg ClassExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, classExists, arg.OrganizationID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createClass = `-- name: CreateClass :one
INSERT INTO class_sections (organization_id, course_id, name)
VALUES ($1, $2, $3)
RETURNING id, course_id, name, 0::bigint AS student_count, 0::bigint AS teacher_count, status
`

type CreateClassParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	CourseID       pgtype.UUID `json:"course_id"`
	Name           string      `json:"name"`
}

type CreateClassRow struct {
	ID           pgtype.UUID `json:"id"`
	CourseID     pgtype.UUID `json:"course_id"`
	Name         string      `json:"name"`
	StudentCount int64       `json:"student_count"`
	TeacherCount int64       `json:"teacher_count"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (CreateClassRow, error) {
	row := q.db.QueryRow(ctx, createClass, arg.OrganizationID, arg.CourseID, arg.Name)
	var i CreateClassRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.StudentCount,
		&i.TeacherCount,
		&i.Status,
	)
	return i, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (organization_id, subject_id, academic_term_id, code, name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, subject_id, academic_term_id, code, name, status
`

type CreateCourseParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	SubjectID      pgtype.UUID `json:"subject_id"`
	AcademicTermID pgtype.UUID `json:"academic_term_id"`
	Code           string      `json:"code"`
	Name           string      `json:"name"`
}

type CreateCourseRow struct {
	ID             pgtype.UUID `json:"id"`
	SubjectID      pgtype.UUID `json:"subject_id"`
	AcademicTermID pgtype.UUID `json:"academic_term_id"`
	Code           string      `json:"code"`
	Name           string      `json:"name"`
	Status         string      `json:"status"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (CreateCourseRow, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.OrganizationID,
		arg.SubjectID,
		arg.AcademicTermID,
		arg.Code,
		arg.Name,
	)
	var i CreateCourseRow
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.AcademicTermID,
		&i.Code,
		&i.Name,
		&i.Status,
	)
	return i, err
}

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (organization_id, code, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, description, status
`

type CreateSubjectParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Code           string      `json:"code"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
}

type CreateSubjectRow struct {
	ID          pgtype.UUID `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (CreateSubjectRow, error) {
	row := q.db.QueryRow(ctx, createSubject,
		arg.OrganizationID,
		arg.Code,
		arg.Name,
		arg.Description,
	)
	var i CreateSubjectRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
	)
	return i, err
}

const createTerm = `-- name: CreateTerm :one
INSERT INTO academic_terms (organization_id, name, start_date, end_date)
VALUES ($1, $2, $3, $4)
RETURNING id, name, start_date, end_date, status
`

type CreateTermParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
}

type CreateTermRow struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Status    string      `json:"status"`
}

func (q *Queries) CreateTerm(ctx context.Context, arg CreateTermParams) (CreateTermRow, error) {
	row := q.db.QueryRow(ctx, createTerm,
		arg.OrganizationID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
	)
	var i CreateTermRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
	)
	return i, err
}

const enrollStudent = `-- name: EnrollStudent :one
WITH inserted AS (
    INSERT INTO enrollments (organization_id, class_section_id, membership_id)
    VALUES ($1, $2, $3)
    RETURNING id, membership_id, status
)
SELECT inserted.id, u.id AS user_id, u.display_name, inserted.status
FROM inserted
JOIN organization_memberships m ON m.id = inserted.membership_id
JOIN users u ON u.id = m.user_id
`

type EnrollStudentParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ClassSectionID pgtype.UUID `json:"class_section_id"`
	MembershipID   pgtype.UUID `json:"membership_id"`
}

type EnrollStudentRow struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	DisplayName pgtype.Text `json:"display_name"`
	Status      string      `json:"status"`
}

func (q *Queries) EnrollStudent(ctx context.Context, arg EnrollStudentParams) (EnrollStudentRow, error) {
	row := q.db.QueryRow(ctx, enrollStudent, arg.OrganizationID, arg.ClassSectionID, arg.MembershipID)
	var i EnrollStudentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
	)
	return i, err
}

const getMembershipByUserID = `-- name: GetMembershipByUserID :one
SELECT m.id, m.user_id, array_agg(mr.role) FILTER (WHERE mr.role IS NOT NULL)
FROM organization_memberships m
LEFT JOIN membership_roles mr ON mr.membership_id = m.id
WHERE m.organization_id = $1
  AND m.user_id = $2
  AND m.status = 'ACTIVE'
GROUP BY m.id, m.user_id
`

type GetMembershipByUserIDParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

type GetMembershipByUserIDRow struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	ArrayAgg interface{} `json:"array_agg"`
}

func (q *Queries) GetMembershipByUserID(ctx context.Context, arg GetMembershipByUserIDParams) (GetMembershipByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getMembershipByUserID, arg.OrganizationID, arg.UserID)
	var i GetMembershipByUserIDRow
	err := row.Scan(&i.ID, &i.UserID, &i.ArrayAgg)
	return i, err
}

const isClassTeacher = `-- name: IsClassTeacher :one
SELECT EXISTS (
    SELECT 1
    FROM class_teachers
    WHERE organization_id = $1
      AND class_section_id = $2
      AND membership_id = $3
      AND status = 'ACTIVE'
)
`

type IsClassTeacherParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ClassSectionID pgtype.UUID `json:"class_section_id"`
	MembershipID   pgtype.UUID `json:"membership_id"`
}

func (q *Queries) IsClassTeacher(ctx context.Context, arg IsClassTeacherParams) (bool, error) {
	row := q.db.QueryRow(ctx, isClassTeacher, arg.OrganizationID, arg.ClassSectionID, arg.MembershipID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listClassTeachers = `-- name: ListClassTeachers :many
SELECT ct.id, u.id AS user_id, u.display_name, ct.role, ct.status
FROM class_teachers ct
JOIN organization_memberships m ON m.id = ct.membership_id
JOIN users u ON u.id = m.user_id
WHERE ct.organization_id = $1
  AND ct.class_section_id = $2
  AND ct.status = 'ACTIVE'
ORDER BY u.display_name
`

type ListClassTeachersParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ClassSectionID pgtype.UUID `json:"class_section_id"`
}

type ListClassTeachersRow struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	DisplayName pgtype.Text `json:"display_name"`
	Role        string      `json:"role"`
	Status      string      `json:"status"`
}

func (q *Queries) ListClassTeachers(ctx context.Context, arg ListClassTeachersParams) ([]ListClassTeachersRow, error) {
	rows, err := q.db.Query(ctx, listClassTeachers, arg.OrganizationID, arg.ClassSectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassTeachersRow
	for rows.Next() {
		var i ListClassTeachersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Role,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesAdmin = `-- name: ListClassesAdmin :many
SELECT
    cs.id,
    cs.course_id,
    cs.name,
    (SELECT COUNT(*) FROM enrollments e WHERE e.class_section_id = cs.id AND e.status = 'ACTIVE') AS student_count,
    (SELECT COUNT(*) FROM class_teachers ct WHERE ct.class_section_id = cs.id AND ct.status = 'ACTIVE') AS teacher_count,
    cs.status
FROM class_sections cs
WHERE cs.organization_id = $1
  AND cs.status = 'ACTIVE'
ORDER BY cs.name
`

type ListClassesAdminRow struct {
	ID           pgtype.UUID `json:"id"`
	CourseID     pgtype.UUID `json:"course_id"`
	Name         string      `json:"name"`
	StudentCount int64       `json:"student_count"`
	TeacherCount int64       `json:"teacher_count"`
	Status       string      `json:"status"`
}

func (q *Queries) ListClassesAdmin(ctx context.Context, organizationID pgtype.UUID) ([]ListClassesAdminRow, error) {
	rows, err := q.db.Query(ctx, listClassesAdmin, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassesAdminRow
	for rows.Next() {
		var i ListClassesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Name,
			&i.StudentCount,
			&i.TeacherCount,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesForTeacher = `-- name: ListClassesForTeacher :many
SELECT
    cs.id,
    cs.course_id,
    cs.name,
    (SELECT COUNT(*) FROM enrollments e WHERE e.class_section_id = cs.id AND e.status = 'ACTIVE') AS student_count,
    (SELECT COUNT(*) FROM class_teachers ct WHERE ct.class_section_id = cs.id AND ct.status = 'ACTIVE') AS teacher_count,
    cs.status
FROM class_sections cs
JOIN class_teachers ct ON ct.class_section_id = cs.id AND ct.status = 'ACTIVE'
WHERE cs.organization_id = $1
  AND cs.status = 'ACTIVE'
  AND ct.membership_id = $2
ORDER BY cs.name
`

type ListClassesForTeacherParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	MembershipID   pgtype.UUID `json:"membership_id"`
}

type ListClassesForTeacherRow struct {
	ID           pgtype.UUID `json:"id"`
	CourseID     pgtype.UUID `json:"course_id"`
	Name         string      `json:"name"`
	StudentCount int64       `json:"student_count"`
	TeacherCount int64       `json:"teacher_count"`
	Status       string      `json:"status"`
}

func (q *Queries) ListClassesForTeacher(ctx context.Context, arg ListClassesForTeacherParams) ([]ListClassesForTeacherRow, error) {
	rows, err := q.db.Query(ctx, listClassesForTeacher, arg.OrganizationID, arg.MembershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassesForTeacherRow
	for rows.Next() {
		var i ListClassesForTeacherRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Name,
			&i.StudentCount,
			&i.TeacherCount,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT id, subject_id, academic_term_id, code, name, status
FROM courses
WHERE organization_id = $1
  AND status = 'ACTIVE'
ORDER BY code
`

type ListCoursesRow struct {
	ID             pgtype.UUID `json:"id"`
	SubjectID      pgtype.UUID `json:"subject_id"`
	AcademicTermID pgtype.UUID `json:"academic_term_id"`
	Code           string      `json:"code"`
	Name           string      `json:"name"`
	Status         string      `json:"status"`
}

func (q *Queries) ListCourses(ctx context.Context, organizationID pgtype.UUID) ([]ListCoursesRow, error) {
	rows, err := q.db.Query(ctx, listCourses, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoursesRow
	for rows.Next() {
		var i ListCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.AcademicTermID,
			&i.Code,
			&i.Name,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrollments = `-- name: ListEnrollments :many
SELECT e.id, u.id AS user_id, u.display_name, e.status
FROM enrollments e
JOIN organization_memberships m ON m.id = e.membership_id
JOIN users u ON u.id = m.user_id
WHERE e.organization_id = $1
  AND e.class_section_id = $2
  AND e.status = 'ACTIVE'
ORDER BY u.display_name
`

type ListEnrollmentsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ClassSectionID pgtype.UUID `json:"class_section_id"`
}

type ListEnrollmentsRow struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	DisplayName pgtype.Text `json:"display_name"`
	Status      string      `json:"status"`
}

func (q *Queries) ListEnrollments(ctx context.Context, arg ListEnrollmentsParams) ([]ListEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listEnrollments, arg.OrganizationID, arg.ClassSectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrollmentsRow
	for rows.Next() {
		var i ListEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, code, name, description, status
FROM subjects
WHERE organization_id = $1
  AND status = 'ACTIVE'
ORDER BY code
`

type ListSubjectsRow struct {
	ID          pgtype.UUID `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
}

func (q *Queries) ListSubjects(ctx context.Context, organizationID pgtype.UUID) ([]ListSubjectsRow, error) {
	rows, err := q.db.Query(ctx, listSubjects, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubjectsRow
	for rows.Next() {
		var i ListSubjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerms = `-- name: ListTerms :many
SELECT id, name, start_date, end_date, status
FROM academic_terms
WHERE organization_id = $1
  AND status = 'ACTIVE'
ORDER BY start_date DESC
`

type ListTermsRow struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Status    string      `json:"status"`
}

func (q *Queries) ListTerms(ctx context.Context, organizationID pgtype.UUID) ([]ListTermsRow, error) {
	rows, err := q.db.Query(ctx, listTerms, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTermsRow
	for rows.Next() {
		var i ListTermsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeClassTeacher = `-- name: RemoveClassTeacher :execrows
UPDATE class_teachers
SET status = 'ARCHIVED',
    updated_at = now()
WHERE organization_id = $1
  AND class_section_id = $2
  AND membership_id = $3
  AND status = 'ACTIVE'
`

type RemoveClassTeacherParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ClassSectionID pgtype.UUID `json:"class_section_id"`
	MembershipID   pgtype.UUID `json:"membership_id"`
}

func (q *Queries) RemoveClassTeacher(ctx context.Context, arg RemoveClassTeacherParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeClassTeacher, arg.OrganizationID, arg.ClassSectionID, arg.MembershipID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unenrollStudent = `-- name: UnenrollStudent :execrows
UPDATE enrollments
SET status = 'ARCHIVED',
    updated_at = now()
WHERE organization_id = $1
  AND class_section_id = $2
  AND membership_id = $3
  AND status = 'ACTIVE'
`

type UnenrollStudentParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ClassSectionID pgtype.UUID `json:"class_section_id"`
	MembershipID   pgtype.UUID `json:"membership_id"`
}

func (q *Queries) UnenrollStudent(ctx context.Context, arg UnenrollStudentParams) (int64, error) {
	result, err := q.db.Exec(ctx, unenrollStudent, arg.OrganizationID, arg.ClassSectionID, arg.MembershipID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateClass = `-- name: UpdateClass :one
UPDATE class_sections cs
SET course_id = $3,
    name = $4,
    updated_at = now()
WHERE cs.id = $1
  AND cs.organization_id = $2
  AND cs.status = 'ACTIVE'
RETURNING cs.id AS id,
          cs.course_id AS course_id,
          cs.name AS name,
          (SELECT COUNT(*) FROM enrollments e WHERE e.class_section_id = cs.id AND e.status = 'ACTIVE') AS student_count,
          (SELECT COUNT(*) FROM class_teachers ct WHERE ct.class_section_id = cs.id AND ct.status = 'ACTIVE') AS teacher_count,
          cs.status AS status
`

type UpdateClassParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	CourseID       pgtype.UUID `json:"course_id"`
	Name           string      `json:"name"`
}

type UpdateClassRow struct {
	ID           pgtype.UUID `json:"id"`
	CourseID     pgtype.UUID `json:"course_id"`
	Name         string      `json:"name"`
	StudentCount int64       `json:"student_count"`
	TeacherCount int64       `json:"teacher_count"`
	Status       string      `json:"status"`
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) (UpdateClassRow, error) {
	row := q.db.QueryRow(ctx, updateClass,
		arg.ID,
		arg.OrganizationID,
		arg.CourseID,
		arg.Name,
	)
	var i UpdateClassRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.StudentCount,
		&i.TeacherCount,
		&i.Status,
	)
	return i, err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET subject_id = $3,
    academic_term_id = $4,
    code = $5,
    name = $6,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND status = 'ACTIVE'
RETURNING id, subject_id, academic_term_id, code, name, status
`

type UpdateCourseParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	SubjectID      pgtype.UUID `json:"subject_id"`
	AcademicTermID pgtype.UUID `json:"academic_term_id"`
	Code           string      `json:"code"`
	Name           string      `json:"name"`
}

type UpdateCourseRow struct {
	ID             pgtype.UUID `json:"id"`
	SubjectID      pgtype.UUID `json:"subject_id"`
	AcademicTermID pgtype.UUID `json:"academic_term_id"`
	Code           string      `json:"code"`
	Name           string      `json:"name"`
	Status         string      `json:"status"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (UpdateCourseRow, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.OrganizationID,
		arg.SubjectID,
		arg.AcademicTermID,
		arg.Code,
		arg.Name,
	)
	var i UpdateCourseRow
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.AcademicTermID,
		&i.Code,
		&i.Name,
		&i.Status,
	)
	return i, err
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE subjects
SET code = $3,
    name = $4,
    description = $5,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND status = 'ACTIVE'
RETURNING id, code, name, description, status
`

type UpdateSubjectParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Code           string      `json:"code"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
}

type UpdateSubjectRow struct {
	ID          pgtype.UUID `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (UpdateSubjectRow, error) {
	row := q.db.QueryRow(ctx, updateSubject,
		arg.ID,
		arg.OrganizationID,
		arg.Code,
		arg.Name,
		arg.Description,
	)
	var i UpdateSubjectRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
	)
	return i, err
}

const updateTerm = `-- name: UpdateTerm :one
UPDATE academic_terms
SET name = $3,
    start_date = $4,
    end_date = $5,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND status = 'ACTIVE'
RETURNING id, name, start_date, end_date, status
`

type UpdateTermParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
}

type UpdateTermRow struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Status    string      `json:"status"`
}

func (q *Queries) UpdateTerm(ctx context.Context, arg UpdateTermParams) (UpdateTermRow, error) {
	row := q.db.QueryRow(ctx, updateTerm,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
	)
	var i UpdateTermRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
	)
	return i, err
}
