// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package notificationssqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnread = `-- name: CountUnread :one
SELECT COUNT(*)
FROM notifications
WHERE organization_id = $1
  AND recipient_user_id = $2
  AND is_read = false
`

type CountUnreadParams struct {
	OrganizationID  pgtype.UUID `json:"organization_id"`
	RecipientUserID pgtype.UUID `json:"recipient_user_id"`
}

func (q *Queries) CountUnread(ctx context.Context, arg CountUnreadParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnread, arg.OrganizationID, arg.RecipientUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNotification = `-- name: GetNotification :one
SELECT
  id, organization_id, recipient_user_id, event_type, title, body, metadata_json,
  is_read, read_at, created_at
FROM notifications
WHERE id = $1 AND organization_id = $2 AND recipient_user_id = $3
`

type GetNotificationParams struct {
	ID              pgtype.UUID `json:"id"`
	OrganizationID  pgtype.UUID `json:"organization_id"`
	RecipientUserID pgtype.UUID `json:"recipient_user_id"`
}

func (q *Queries) GetNotification(ctx context.Context, arg GetNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, arg.ID, arg.OrganizationID, arg.RecipientUserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RecipientUserID,
		&i.EventType,
		&i.Title,
		&i.Body,
		&i.MetadataJson,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (
  organization_id, recipient_user_id, event_type, title, body, metadata_json
) VALUES (
  $1, $2, $3, $4, $5, $6::jsonb
)
RETURNING id, organization_id, recipient_user_id, event_type, title, body, metadata_json, is_read, read_at, created_at
`

type InsertNotificationParams struct {
	OrganizationID  pgtype.UUID `json:"organization_id"`
	RecipientUserID pgtype.UUID `json:"recipient_user_id"`
	EventType       string      `json:"event_type"`
	Title           string      `json:"title"`
	Body            string      `json:"body"`
	Column6         []byte      `json:"column_6"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.OrganizationID,
		arg.RecipientUserID,
		arg.EventType,
		arg.Title,
		arg.Body,
		arg.Column6,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RecipientUserID,
		&i.EventType,
		&i.Title,
		&i.Body,
		&i.MetadataJson,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAssessmentTargetStudentUserIDs = `-- name: ListAssessmentTargetStudentUserIDs :many
SELECT DISTINCT m.user_id
FROM assessment_targets t
JOIN enrollments e
  ON e.organization_id = t.organization_id
 AND e.class_section_id = t.class_section_id
 AND e.status = 'ACTIVE'
JOIN organization_memberships m ON m.id = e.membership_id
WHERE t.organization_id = $1
  AND t.assessment_id = $2
  AND t.status = 'ACTIVE'
  AND m.status = 'ACTIVE'
`

type ListAssessmentTargetStudentUserIDsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
}

// Expand the active target classes of an assessment into distinct
// student user ids for assessment.published notifications.
func (q *Queries) ListAssessmentTargetStudentUserIDs(ctx context.Context, arg ListAssessmentTargetStudentUserIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAssessmentTargetStudentUserIDs, arg.OrganizationID, arg.AssessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassStudentUserIDs = `-- name: ListClassStudentUserIDs :many
SELECT m.user_id
FROM enrollments e
JOIN organization_memberships m ON m.id = e.membership_id
WHERE e.organization_id = $1
  AND e.class_section_id = $2
  AND e.status = 'ACTIVE'
  AND m.status = 'ACTIVE'
`

type ListClassStudentUserIDsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ClassSectionID pgtype.UUID `json:"class_section_id"`
}

// Used by the resources publish notifier to expand a class-scoped
// resource to its currently enrolled students.
func (q *Queries) ListClassStudentUserIDs(ctx context.Context, arg ListClassStudentUserIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listClassStudentUserIDs, arg.OrganizationID, arg.ClassSectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT
  id, organization_id, recipient_user_id, event_type, title, body, metadata_json,
  is_read, read_at, created_at
FROM notifications
WHERE organization_id = $1
  AND recipient_user_id = $2
  AND ($3::timestamptz IS NULL OR created_at < $3::timestamptz)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListNotificationsParams struct {
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	RecipientUserID pgtype.UUID        `json:"recipient_user_id"`
	Column3         pgtype.Timestamptz `json:"column_3"`
	Limit           int32              `json:"limit"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.OrganizationID,
		arg.RecipientUserID,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RecipientUserID,
			&i.EventType,
			&i.Title,
			&i.Body,
			&i.MetadataJson,
			&i.IsRead,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRead = `-- name: MarkRead :one
UPDATE notifications
SET is_read = true,
    read_at = COALESCE(read_at, now())
WHERE id = $1 AND organization_id = $2 AND recipient_user_id = $3
RETURNING id, organization_id, recipient_user_id, event_type, title, body, metadata_json, is_read, read_at, created_at
`

type MarkReadParams struct {
	ID              pgtype.UUID `json:"id"`
	OrganizationID  pgtype.UUID `json:"organization_id"`
	RecipientUserID pgtype.UUID `json:"recipient_user_id"`
}

func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markRead, arg.ID, arg.OrganizationID, arg.RecipientUserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RecipientUserID,
		&i.EventType,
		&i.Title,
		&i.Body,
		&i.MetadataJson,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}
