// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package resourcessqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveResource = `-- name: ArchiveResource :exec
UPDATE resources
SET status = 'ARCHIVED', updated_at = now()
WHERE id = $1 AND organization_id = $2
`

type ArchiveResourceParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ArchiveResource(ctx context.Context, arg ArchiveResourceParams) error {
	_, err := q.db.Exec(ctx, archiveResource, arg.ID, arg.OrganizationID)
	return err
}

const archiveResourceFile = `-- name: ArchiveResourceFile :exec
UPDATE resource_files
SET status = 'ARCHIVED'
WHERE id = $1 AND organization_id = $2
`

type ArchiveResourceFileParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ArchiveResourceFile(ctx context.Context, arg ArchiveResourceFileParams) error {
	_, err := q.db.Exec(ctx, archiveResourceFile, arg.ID, arg.OrganizationID)
	return err
}

const createResource = `-- name: CreateResource :one
INSERT INTO resources (
  organization_id, title, description, context_type, context_id, status, created_by
) VALUES (
  $1, $2, $3, $4::resource_context_type, $5, 'DRAFT', $6
)
RETURNING id, organization_id, title, description, context_type::text, context_id, status::text, created_by, created_at, updated_at, published_at
`

type CreateResourceParams struct {
	OrganizationID pgtype.UUID         `json:"organization_id"`
	Title          string              `json:"title"`
	Description    pgtype.Text         `json:"description"`
	Column4        ResourceContextType `json:"column_4"`
	ContextID      pgtype.UUID         `json:"context_id"`
	CreatedBy      pgtype.UUID         `json:"created_by"`
}

type CreateResourceRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	ContextType    string             `json:"context_type"`
	ContextID      pgtype.UUID        `json:"context_id"`
	Status         string             `json:"status"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (CreateResourceRow, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.OrganizationID,
		arg.Title,
		arg.Description,
		arg.Column4,
		arg.ContextID,
		arg.CreatedBy,
	)
	var i CreateResourceRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.Description,
		&i.ContextType,
		&i.ContextID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const createResourceFile = `-- name: CreateResourceFile :one
INSERT INTO resource_files (
  resource_id, organization_id, original_name, storage_key, content_type, size_bytes, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, resource_id, organization_id, original_name, storage_key, content_type, size_bytes, status::text, created_by, created_at
`

type CreateResourceFileParams struct {
	ResourceID     pgtype.UUID `json:"resource_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	OriginalName   string      `json:"original_name"`
	StorageKey     string      `json:"storage_key"`
	ContentType    string      `json:"content_type"`
	SizeBytes      int64       `json:"size_bytes"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

type CreateResourceFileRow struct {
	ID             pgtype.UUID        `json:"id"`
	ResourceID     pgtype.UUID        `json:"resource_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	OriginalName   string             `json:"original_name"`
	StorageKey     string             `json:"storage_key"`
	ContentType    string             `json:"content_type"`
	SizeBytes      int64              `json:"size_bytes"`
	Status         string             `json:"status"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateResourceFile(ctx context.Context, arg CreateResourceFileParams) (CreateResourceFileRow, error) {
	row := q.db.QueryRow(ctx, createResourceFile,
		arg.ResourceID,
		arg.OrganizationID,
		arg.OriginalName,
		arg.StorageKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.CreatedBy,
	)
	var i CreateResourceFileRow
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.OrganizationID,
		&i.OriginalName,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveResourceFile = `-- name: GetActiveResourceFile :one
SELECT
  id, resource_id, organization_id, original_name, storage_key, content_type, size_bytes,
  status::text, created_by, created_at
FROM resource_files
WHERE resource_id = $1 AND organization_id = $2 AND status = 'ACTIVE'
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveResourceFileParams struct {
	ResourceID     pgtype.UUID `json:"resource_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetActiveResourceFileRow struct {
	ID             pgtype.UUID        `json:"id"`
	ResourceID     pgtype.UUID        `json:"resource_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	OriginalName   string             `json:"original_name"`
	StorageKey     string             `json:"storage_key"`
	ContentType    string             `json:"content_type"`
	SizeBytes      int64              `json:"size_bytes"`
	Status         string             `json:"status"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetActiveResourceFile(ctx context.Context, arg GetActiveResourceFileParams) (GetActiveResourceFileRow, error) {
	row := q.db.QueryRow(ctx, getActiveResourceFile, arg.ResourceID, arg.OrganizationID)
	var i GetActiveResourceFileRow
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.OrganizationID,
		&i.OriginalName,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getResource = `-- name: GetResource :one
SELECT
  id, organization_id, title, description, context_type::text, context_id, status::text,
  created_by, created_at, updated_at, published_at
FROM resources
WHERE id = $1 AND organization_id = $2
`

type GetResourceParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetResourceRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	ContextType    string             `json:"context_type"`
	ContextID      pgtype.UUID        `json:"context_id"`
	Status         string             `json:"status"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) GetResource(ctx context.Context, arg GetResourceParams) (GetResourceRow, error) {
	row := q.db.QueryRow(ctx, getResource, arg.ID, arg.OrganizationID)
	var i GetResourceRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.Description,
		&i.ContextType,
		&i.ContextID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listResourceFiles = `-- name: ListResourceFiles :many
SELECT
  id, resource_id, organization_id, original_name, storage_key, content_type, size_bytes,
  status::text, created_by, created_at
FROM resource_files
WHERE resource_id = $1 AND organization_id = $2
ORDER BY created_at DESC
`

type ListResourceFilesParams struct {
	ResourceID     pgtype.UUID `json:"resource_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListResourceFilesRow struct {
	ID             pgtype.UUID        `json:"id"`
	ResourceID     pgtype.UUID        `json:"resource_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	OriginalName   string             `json:"original_name"`
	StorageKey     string             `json:"storage_key"`
	ContentType    string             `json:"content_type"`
	SizeBytes      int64              `json:"size_bytes"`
	Status         string             `json:"status"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListResourceFiles(ctx context.Context, arg ListResourceFilesParams) ([]ListResourceFilesRow, error) {
	rows, err := q.db.Query(ctx, listResourceFiles, arg.ResourceID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResourceFilesRow
	for rows.Next() {
		var i ListResourceFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.OrganizationID,
			&i.OriginalName,
			&i.StorageKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
SELECT
  id, organization_id, title, description, context_type::text, context_id, status::text,
  created_by, created_at, updated_at, published_at
FROM resources
WHERE organization_id = $1
  AND status::text = ANY($2::text[])
ORDER BY updated_at DESC
`

type ListResourcesParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Column2        []string    `json:"column_2"`
}

type ListResourcesRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	ContextType    string             `json:"context_type"`
	ContextID      pgtype.UUID        `json:"context_id"`
	Status         string             `json:"status"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ListResources(ctx context.Context, arg ListResourcesParams) ([]ListResourcesRow, error) {
	rows, err := q.db.Query(ctx, listResources, arg.OrganizationID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResourcesRow
	for rows.Next() {
		var i ListResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Title,
			&i.Description,
			&i.ContextType,
			&i.ContextID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResourceStatus = `-- name: UpdateResourceStatus :one
UPDATE resources
SET
  status = $3::resource_status,
  published_at = CASE WHEN $3::resource_status = 'PUBLISHED' THEN now() ELSE published_at END,
  updated_at = now()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, title, description, context_type::text, context_id, status::text, created_by, created_at, updated_at, published_at
`

type UpdateResourceStatusParams struct {
	ID             pgtype.UUID    `json:"id"`
	OrganizationID pgtype.UUID    `json:"organization_id"`
	Column3        ResourceStatus `json:"column_3"`
}

type UpdateResourceStatusRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	ContextType    string             `json:"context_type"`
	ContextID      pgtype.UUID        `json:"context_id"`
	Status         string             `json:"status"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (UpdateResourceStatusRow, error) {
	row := q.db.QueryRow(ctx, updateResourceStatus, arg.ID, arg.OrganizationID, arg.Column3)
	var i UpdateResourceStatusRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.Description,
		&i.ContextType,
		&i.ContextID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}
