// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package attemptssqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStudentAttempts = `-- name: CountStudentAttempts :one
SELECT COUNT(*)
FROM attempts
WHERE organization_id = $1
  AND student_user_id = $2
  AND assessment_id = $3
`

type CountStudentAttemptsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	StudentUserID  pgtype.UUID `json:"student_user_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
}

func (q *Queries) CountStudentAttempts(ctx context.Context, arg CountStudentAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentAttempts, arg.OrganizationID, arg.StudentUserID, arg.AssessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO attempts (organization_id, assessment_id, student_user_id, publication_id, status, started_at, expires_at)
VALUES ($1, $2, $3, $4, 'IN_PROGRESS', $5, $6)
RETURNING id, organization_id, assessment_id, publication_id, status, started_at, expires_at, submitted_at, score, max_score, grading_status
`

type CreateAttemptParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AssessmentID   pgtype.UUID        `json:"assessment_id"`
	StudentUserID  pgtype.UUID        `json:"student_user_id"`
	PublicationID  pgtype.UUID        `json:"publication_id"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type CreateAttemptRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AssessmentID   pgtype.UUID        `json:"assessment_id"`
	PublicationID  pgtype.UUID        `json:"publication_id"`
	Status         string             `json:"status"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	Score          pgtype.Numeric     `json:"score"`
	MaxScore       pgtype.Numeric     `json:"max_score"`
	GradingStatus  pgtype.Text        `json:"grading_status"`
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (CreateAttemptRow, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.OrganizationID,
		arg.AssessmentID,
		arg.StudentUserID,
		arg.PublicationID,
		arg.StartedAt,
		arg.ExpiresAt,
	)
	var i CreateAttemptRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AssessmentID,
		&i.PublicationID,
		&i.Status,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.Score,
		&i.MaxScore,
		&i.GradingStatus,
	)
	return i, err
}

const createAttemptItem = `-- name: CreateAttemptItem :exec
INSERT INTO attempt_items (organization_id, attempt_id, question_version_id, position, points, prompt_json, choices_json, answer_key_json)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAttemptItemParams struct {
	OrganizationID    pgtype.UUID    `json:"organization_id"`
	AttemptID         pgtype.UUID    `json:"attempt_id"`
	QuestionVersionID pgtype.UUID    `json:"question_version_id"`
	Position          int32          `json:"position"`
	Points            pgtype.Numeric `json:"points"`
	PromptJson        []byte         `json:"prompt_json"`
	ChoicesJson       []byte         `json:"choices_json"`
	AnswerKeyJson     []byte         `json:"answer_key_json"`
}

func (q *Queries) CreateAttemptItem(ctx context.Context, arg CreateAttemptItemParams) error {
	_, err := q.db.Exec(ctx, createAttemptItem,
		arg.OrganizationID,
		arg.AttemptID,
		arg.QuestionVersionID,
		arg.Position,
		arg.Points,
		arg.PromptJson,
		arg.ChoicesJson,
		arg.AnswerKeyJson,
	)
	return err
}

const getAttempt = `-- name: GetAttempt :one
SELECT
    a.id,
    a.organization_id,
    a.assessment_id,
    a.publication_id,
    a.status,
    a.started_at,
    a.expires_at,
    a.submitted_at,
    a.score,
    a.max_score,
    a.grading_status
FROM attempts a
WHERE a.id = $1
  AND a.organization_id = $2
  AND a.student_user_id = $3
LIMIT 1
`

type GetAttemptParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	StudentUserID  pgtype.UUID `json:"student_user_id"`
}

type GetAttemptRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AssessmentID   pgtype.UUID        `json:"assessment_id"`
	PublicationID  pgtype.UUID        `json:"publication_id"`
	Status         string             `json:"status"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	Score          pgtype.Numeric     `json:"score"`
	MaxScore       pgtype.Numeric     `json:"max_score"`
	GradingStatus  pgtype.Text        `json:"grading_status"`
}

func (q *Queries) GetAttempt(ctx context.Context, arg GetAttemptParams) (GetAttemptRow, error) {
	row := q.db.QueryRow(ctx, getAttempt, arg.ID, arg.OrganizationID, arg.StudentUserID)
	var i GetAttemptRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AssessmentID,
		&i.PublicationID,
		&i.Status,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.Score,
		&i.MaxScore,
		&i.GradingStatus,
	)
	return i, err
}

const getAttemptForUpdate = `-- name: GetAttemptForUpdate :one
SELECT
    id,
    organization_id,
    assessment_id,
    publication_id,
    status,
    started_at,
    expires_at,
    submitted_at,
    score,
    max_score,
    grading_status
FROM attempts
WHERE id = $1
  AND organization_id = $2
  AND student_user_id = $3
FOR UPDATE
`

type GetAttemptForUpdateParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	StudentUserID  pgtype.UUID `json:"student_user_id"`
}

type GetAttemptForUpdateRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AssessmentID   pgtype.UUID        `json:"assessment_id"`
	PublicationID  pgtype.UUID        `json:"publication_id"`
	Status         string             `json:"status"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	Score          pgtype.Numeric     `json:"score"`
	MaxScore       pgtype.Numeric     `json:"max_score"`
	GradingStatus  pgtype.Text        `json:"grading_status"`
}

func (q *Queries) GetAttemptForUpdate(ctx context.Context, arg GetAttemptForUpdateParams) (GetAttemptForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAttemptForUpdate, arg.ID, arg.OrganizationID, arg.StudentUserID)
	var i GetAttemptForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AssessmentID,
		&i.PublicationID,
		&i.Status,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.Score,
		&i.MaxScore,
		&i.GradingStatus,
	)
	return i, err
}

const getAttemptItems = `-- name: GetAttemptItems :many
SELECT
    ai.id,
    ai.question_version_id,
    ai.position,
    ai.points::text,
    ai.prompt_json,
    ai.choices_json,
    aa.answer_payload,
    ai.answer_key_json,
    aa.revision,
    aa.answered_at
FROM attempt_items ai
LEFT JOIN attempt_answers aa
    ON aa.attempt_item_id = ai.id
    AND aa.organization_id = ai.organization_id
    AND aa.attempt_id = ai.attempt_id
WHERE ai.attempt_id = $1
  AND ai.organization_id = $2
ORDER BY ai.position
`

type GetAttemptItemsParams struct {
	AttemptID      pgtype.UUID `json:"attempt_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetAttemptItemsRow struct {
	ID                pgtype.UUID        `json:"id"`
	QuestionVersionID pgtype.UUID        `json:"question_version_id"`
	Position          int32              `json:"position"`
	AiPoints          string             `json:"ai_points"`
	PromptJson        []byte             `json:"prompt_json"`
	ChoicesJson       []byte             `json:"choices_json"`
	AnswerPayload     []byte             `json:"answer_payload"`
	AnswerKeyJson     []byte             `json:"answer_key_json"`
	Revision          pgtype.Int8        `json:"revision"`
	AnsweredAt        pgtype.Timestamptz `json:"answered_at"`
}

func (q *Queries) GetAttemptItems(ctx context.Context, arg GetAttemptItemsParams) ([]GetAttemptItemsRow, error) {
	rows, err := q.db.Query(ctx, getAttemptItems, arg.AttemptID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttemptItemsRow
	for rows.Next() {
		var i GetAttemptItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionVersionID,
			&i.Position,
			&i.AiPoints,
			&i.PromptJson,
			&i.ChoicesJson,
			&i.AnswerPayload,
			&i.AnswerKeyJson,
			&i.Revision,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInProgressAttempt = `-- name: GetInProgressAttempt :one
SELECT id, organization_id, assessment_id, publication_id, status, started_at, expires_at, submitted_at, score, max_score, grading_status
FROM attempts
WHERE organization_id = $1
  AND student_user_id = $2
  AND assessment_id = $3
  AND status = 'IN_PROGRESS'
LIMIT 1
`

type GetInProgressAttemptParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	StudentUserID  pgtype.UUID `json:"student_user_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
}

type GetInProgressAttemptRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AssessmentID   pgtype.UUID        `json:"assessment_id"`
	PublicationID  pgtype.UUID        `json:"publication_id"`
	Status         string             `json:"status"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	Score          pgtype.Numeric     `json:"score"`
	MaxScore       pgtype.Numeric     `json:"max_score"`
	GradingStatus  pgtype.Text        `json:"grading_status"`
}

func (q *Queries) GetInProgressAttempt(ctx context.Context, arg GetInProgressAttemptParams) (GetInProgressAttemptRow, error) {
	row := q.db.QueryRow(ctx, getInProgressAttempt, arg.OrganizationID, arg.StudentUserID, arg.AssessmentID)
	var i GetInProgressAttemptRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AssessmentID,
		&i.PublicationID,
		&i.Status,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.Score,
		&i.MaxScore,
		&i.GradingStatus,
	)
	return i, err
}

const getLatestPublication = `-- name: GetLatestPublication :one
SELECT id, snapshot_json, published_at
FROM assessment_publications
WHERE organization_id = $1
  AND assessment_id = $2
ORDER BY version DESC
LIMIT 1
`

type GetLatestPublicationParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AssessmentID   pgtype.UUID `json:"assessment_id"`
}

type GetLatestPublicationRow struct {
	ID           pgtype.UUID        `json:"id"`
	SnapshotJson []byte             `json:"snapshot_json"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) GetLatestPublication(ctx context.Context, arg GetLatestPublicationParams) (GetLatestPublicationRow, error) {
	row := q.db.QueryRow(ctx, getLatestPublication, arg.OrganizationID, arg.AssessmentID)
	var i GetLatestPublicationRow
	err := row.Scan(&i.ID, &i.SnapshotJson, &i.PublishedAt)
	return i, err
}

const itemExists = `-- name: ItemExists :one
SELECT EXISTS (
    SELECT 1
    FROM attempt_items
    WHERE id = $1
      AND attempt_id = $2
      AND organization_id = $3
)
`

type ItemExistsParams struct {
	ID             pgtype.UUID `json:"id"`
	AttemptID      pgtype.UUID `json:"attempt_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ItemExists(ctx context.Context, arg ItemExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, itemExists, arg.ID, arg.AttemptID, arg.OrganizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAssignedAssessments = `-- name: ListAssignedAssessments :many
SELECT a.id, a.title, a.status, a.duration_minutes, a.max_attempts, a.revision, a.opens_at, a.closes_at, ap.id AS publication_id, ap.published_at, COALESCE(used.cnt, 0) AS attempts_used
FROM assessments a
JOIN assessment_targets t ON t.assessment_id = a.id AND t.status = 'ACTIVE'
JOIN class_sections cs ON cs.id = t.class_section_id AND cs.status = 'ACTIVE'
JOIN enrollments e ON e.class_section_id = t.class_section_id AND e.status = 'ACTIVE'
JOIN organization_memberships m ON m.id = e.membership_id AND m.user_id = $1 AND m.organization_id = $2 AND m.status = 'ACTIVE'
LEFT JOIN LATERAL (
    SELECT id, published_at
    FROM assessment_publications
    WHERE assessment_id = a.id AND organization_id = $2
    ORDER BY version DESC
    LIMIT 1
) ap ON true
LEFT JOIN LATERAL (
    SELECT COUNT(*)::int AS cnt
    FROM attempts att
    WHERE att.organization_id = $2
      AND att.student_user_id = $1
      AND att.assessment_id = a.id
) used ON true
WHERE a.organization_id = $2
  AND a.status IN ('OPEN', 'PUBLISHED')
  AND ap.id IS NOT NULL
ORDER BY a.created_at DESC
`

type ListAssignedAssessmentsParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListAssignedAssessmentsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	Status          string             `json:"status"`
	DurationMinutes int32              `json:"duration_minutes"`
	MaxAttempts     int32              `json:"max_attempts"`
	Revision        int32              `json:"revision"`
	OpensAt         pgtype.Timestamptz `json:"opens_at"`
	ClosesAt        pgtype.Timestamptz `json:"closes_at"`
	PublicationID   pgtype.UUID        `json:"publication_id"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	AttemptsUsed    int32              `json:"attempts_used"`
}

func (q *Queries) ListAssignedAssessments(ctx context.Context, arg ListAssignedAssessmentsParams) ([]ListAssignedAssessmentsRow, error) {
	rows, err := q.db.Query(ctx, listAssignedAssessments, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignedAssessmentsRow
	for rows.Next() {
		var i ListAssignedAssessmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.DurationMinutes,
			&i.MaxAttempts,
			&i.Revision,
			&i.OpensAt,
			&i.ClosesAt,
			&i.PublicationID,
			&i.PublishedAt,
			&i.AttemptsUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentAttempts = `-- name: ListStudentAttempts :many
SELECT a.id, a.assessment_id, a.publication_id, a.status, a.started_at, a.expires_at, a.submitted_at, a.created_at, CASE WHEN a.score IS NULL THEN ''::text ELSE a.score::text END AS score, CASE WHEN a.max_score IS NULL THEN ''::text ELSE a.max_score::text END AS max_score, a.grading_status, asmt.title AS assessment_title
FROM attempts a
JOIN assessments asmt ON asmt.id = a.assessment_id AND asmt.organization_id = a.organization_id
WHERE a.organization_id = $1
  AND a.student_user_id = $2
  AND ($3::text = '' OR a.created_at < $3::timestamptz OR (a.created_at = $3::timestamptz AND a.id::text < $4))
ORDER BY a.created_at DESC, a.id DESC
LIMIT $5::int
`

type ListStudentAttemptsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	StudentUserID  pgtype.UUID `json:"student_user_id"`
	CursorKey      string      `json:"cursor_key"`
	CursorID       pgtype.UUID `json:"cursor_id"`
	PageLimit      int32       `json:"page_limit"`
}

type ListStudentAttemptsRow struct {
	ID              pgtype.UUID        `json:"id"`
	AssessmentID    pgtype.UUID        `json:"assessment_id"`
	PublicationID   pgtype.UUID        `json:"publication_id"`
	Status          string             `json:"status"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Score           string             `json:"score"`
	MaxScore        string             `json:"max_score"`
	GradingStatus   pgtype.Text        `json:"grading_status"`
	AssessmentTitle string             `json:"assessment_title"`
}

func (q *Queries) ListStudentAttempts(ctx context.Context, arg ListStudentAttemptsParams) ([]ListStudentAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listStudentAttempts,
		arg.OrganizationID,
		arg.StudentUserID,
		arg.CursorKey,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentAttemptsRow
	for rows.Next() {
		var i ListStudentAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.PublicationID,
			&i.Status,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.Score,
			&i.MaxScore,
			&i.GradingStatus,
			&i.AssessmentTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttemptExpired = `-- name: MarkAttemptExpired :exec
UPDATE attempts
SET status = 'EXPIRED', updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND student_user_id = $3
`

type MarkAttemptExpiredParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	StudentUserID  pgtype.UUID `json:"student_user_id"`
}

func (q *Queries) MarkAttemptExpired(ctx context.Context, arg MarkAttemptExpiredParams) error {
	_, err := q.db.Exec(ctx, markAttemptExpired, arg.ID, arg.OrganizationID, arg.StudentUserID)
	return err
}

const submitAttempt = `-- name: SubmitAttempt :one
UPDATE attempts
SET status = 'SUBMITTED',
    submitted_at = now(),
    score = $4,
    max_score = $5,
    grading_status = $6,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND student_user_id = $3
  AND status = 'IN_PROGRESS'
RETURNING submitted_at, score::text, max_score::text, grading_status
`

type SubmitAttemptParams struct {
	ID             pgtype.UUID    `json:"id"`
	OrganizationID pgtype.UUID    `json:"organization_id"`
	StudentUserID  pgtype.UUID    `json:"student_user_id"`
	Score          pgtype.Numeric `json:"score"`
	MaxScore       pgtype.Numeric `json:"max_score"`
	GradingStatus  pgtype.Text    `json:"grading_status"`
}

type SubmitAttemptRow struct {
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	Score         string             `json:"score"`
	MaxScore      string             `json:"max_score"`
	GradingStatus pgtype.Text        `json:"grading_status"`
}

func (q *Queries) SubmitAttempt(ctx context.Context, arg SubmitAttemptParams) (SubmitAttemptRow, error) {
	row := q.db.QueryRow(ctx, submitAttempt,
		arg.ID,
		arg.OrganizationID,
		arg.StudentUserID,
		arg.Score,
		arg.MaxScore,
		arg.GradingStatus,
	)
	var i SubmitAttemptRow
	err := row.Scan(
		&i.SubmittedAt,
		&i.Score,
		&i.MaxScore,
		&i.GradingStatus,
	)
	return i, err
}

const upsertAnswer = `-- name: UpsertAnswer :one
INSERT INTO attempt_answers (
    organization_id,
    attempt_id,
    attempt_item_id,
    answer_payload,
    revision,
    answered_at,
    updated_at
) VALUES ($1, $2, $3, $4, 1, now(), now())
ON CONFLICT (organization_id, attempt_id, attempt_item_id)
DO UPDATE SET
    answer_payload = EXCLUDED.answer_payload,
    revision = attempt_answers.revision + 1,
    answered_at = now(),
    updated_at = now()
RETURNING revision, answered_at, answer_payload
`

type UpsertAnswerParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	AttemptID      pgtype.UUID `json:"attempt_id"`
	AttemptItemID  pgtype.UUID `json:"attempt_item_id"`
	AnswerPayload  []byte      `json:"answer_payload"`
}

type UpsertAnswerRow struct {
	Revision      int64              `json:"revision"`
	AnsweredAt    pgtype.Timestamptz `json:"answered_at"`
	AnswerPayload []byte             `json:"answer_payload"`
}

func (q *Queries) UpsertAnswer(ctx context.Context, arg UpsertAnswerParams) (UpsertAnswerRow, error) {
	row := q.db.QueryRow(ctx, upsertAnswer,
		arg.OrganizationID,
		arg.AttemptID,
		arg.AttemptItemID,
		arg.AnswerPayload,
	)
	var i UpsertAnswerRow
	err := row.Scan(&i.Revision, &i.AnsweredAt, &i.AnswerPayload)
	return i, err
}
